### ISSUE TITLE
How to deal with large images

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTsR#182]
I have a 2000x2000x1400 dataset which actually has four specimens in the FOV. I came up with a simple procedure, where I heavily resample to volume (about 300x300x200), threshold, run connected components (none of them touch each other), mask and save individual samples as new volumes in Slicer. 

I have a bunch of these kind of volumes to process in batch, so I am trying to do the same with ANTsR. Image loads fine, but fi=resampleImage (img, c(.1, .1, .1)) never finishes. At this point it is going on about 6 minutes, and using 175GB of RAM. In Slicer it takes about a minute for the whole workflow. 

Is there a trick to deal with large images in ANTsR?

**Comment by muschellij2** [comment]
Have you tried

resampleImage(img, resampleParams = c(300, 300, 200), useVoxels = TRUE)

and can you print img@components

John

**Comment by muratmaga** [comment]
Yep, still the same behavior, RAM usage climbs to $175GB in a few minutes, after which I have to cancel the task, as I am afraid it is going to stall the system.
Number of components in the image is 1.

**Comment by stnava** [comment]
see the code:

```
> resampleImage
function (image, resampleParams, useVoxels = FALSE, interpType = 1) 
{
    if (image@components == 1) {
        inimg <- antsImageClone(image, "double")
        outimg <- antsImageClone(image, "double")
        rsampar <- paste(resampleParams, collapse = "x")
        args <- list(image@dimension, inimg, outimg, rsampar, 
            as.numeric(useVoxels), interpType)
        k <- .int_antsProcessArguments(args)
        retval <- .Call("ResampleImage", k)
        outimg <- antsImageClone(outimg, image@pixeltype)
        return(outimg)
    }
    if (image@components > 1) {
        mychanns = splitChannels(image)
        for (k in 1:length(mychanns)) {
            inimg <- antsImageClone(mychanns[[k]], "double")
            outimg <- antsImageClone(mychanns[[k]], "double")
            rsampar <- paste(resampleParams, collapse = "x")
            args <- list(image@dimension, inimg, outimg, rsampar, 
                as.numeric(useVoxels), interpType)
            temp <- .int_antsProcessArguments(args)
            retval <- .Call("ResampleImage", temp)
            mychanns[[k]] <- antsImageClone(outimg, image@pixeltype)
        }
        return(mergeChannels(mychanns))
    }
}
<environment: namespace:ANTsRCore>
```

could use a refactoring, for sure.

**Comment by stnava** [comment]
in brief, it casts to double and copies the image.

**Comment by stnava** [comment]
i resolved this with https://github.com/ANTsX/ANTsRCore/commit/b04d955a0dc5e343944b23fd90352c9d1b38e74c

necessitates reinstall of antsrcore
