### ISSUE TITLE
problem installing within R using devtools

### ISSUE THREAD

**Issue by ptsii** [ANTsX/ANTsR#187]
On one of my machines I get an error trying to install ANTsR from within R using the devtools method.  Specifically, when I do the install_github("stnava/ITKR") step I get a segfault:

> install_github("stnava/ITKR")
Downloading GitHub repo stnava/ITKR@master
from URL https://api.github.com/repos/stnava/ITKR/zipball/master
Installing ITKR

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: .Call("digest", object, as.integer(algoint), as.integer(length),     as.integer(skip), as.integer(raw), PACKAGE = "digest")
 2: digest::digest(..., algo = algo)
 3: `_cache`$digest(c(body(`_f`), args, lapply(`_additional`, function(x) eval(x[[2L]],     environment(x)))))
 4: available_packages(repos, type)
 5: tools::package_dependencies(pkgs, db = available, which = top_dep)
 6: find_deps(pkg, available_packages(repos, type), top_dep = dependencies)
 7: force(code)
 8: withr::with_collate("C", x[order(tolower(x), x)])
 9: sort_ci(find_deps(pkg, available_packages(repos, type), top_dep = dependencies))
10: package_deps(deps, repos = repos, type = type)
11: rbind(cran_deps, remote_deps)
12: filter_duplicate_deps(package_deps(deps, repos = repos, type = type),     installing$remote_deps %||% remote_deps(pkg))
13: dev_package_deps(pkg, repos = repos, dependencies = dependencies,     type = type)
14: install_deps(pkg, dependencies = initial_deps, upgrade = upgrade_dependencies,     threads = threads, force_deps = force_deps, quiet = quiet,     ..., out_dir = out_dir, skip_if_log_exists = skip_if_log_exists)
15: install(source, ..., quiet = quiet, metadata = metadata, out_dir = out_dir,     skip_if_log_exists = skip_if_log_exists)
16: install_remote(..., quiet = quiet)
17: doTryCatch(return(expr), name, parentenv, handler)
18: tryCatchOne(expr, names, parentenv, handlers[[1L]])
19: tryCatchList(expr, classes, parentenv, handlers)
20: tryCatch(install_remote(..., quiet = quiet), error = function(e) {    if (!quiet) {        message("Installation failed: ", conditionMessage(e))    }    FALSE})
21: FUN(X[[i]], ...)
22: vapply(remotes, try_install_remote, ..., FUN.VALUE = logical(1))
23: install_remotes(remotes, quiet = quiet, ...)
24: install_github("stnava/ITKR")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 

Any thoughts about what might be going wrong?  I tried completely uninstalling R and trying again, but that doesn't change things.

-Tom

**Comment by stnava** [comment]
No ideas here.  Would need more info to be able to reproduce, if that is possible.

**Comment by ptsii** [comment]
For future reference (if anyone else gets this error): I apparently hadn't completely removed all instances of R, the libraries, etc.  After I did this, and reinstalled R from scratch, I was then able to install ANTsR from within R using the devtools method.
