### ISSUE TITLE
antsMotionCorr: output write displacement field transforms

### ISSUE THREAD

**Issue by VeroAra** [ANTsX/ANTsR#190]
Hi!
I am working with the command "antsMotionCorr" in Rstudio. Registration of my images work good but I would like to obtain as the displacement transform as an output to check out how these transformations are done.

In ANTS, the following parameter "-w 1" appears to write out the displacement field (a 4D displacement field that captures the affine induced motion at each voxel). However, when using it in Rstudio (w=1), it does not work and the session is aborted.

Does anyone know how this output can be obtained? 
Thank you in advanced,

` aimg <- new("antsImage", "float", 2) #imagen de referencia a crear
    mocoImg <- new("antsImage", "float", 3) # imagen resultado 
    mocoParams <- new("antsMatrix", "double")
    
    antsMotionCorr( list( d = 2 , a = regLABEL_LX, o = aimg ) ) # average img created to work as a reference
    antsMotionCorr( list( d = 2 ,
                          o = list( mocoParams , mocoImg , aimg ) ,
                          m = list( name = "CC" , aimg , movingImage=regCONTROL_CX , metricWeight=1 , radius=1 , samplingStrategy="Regular", samplingPercentage=0.2 ) ,
                          t = "SyN[0.03, 3, 0]" , i = "1000x1000",
                          u = 1, e = 1 , s = "0x0", f = "2x1", n=1 ,
                          v = as.numeric(TRUE) )) #TRUE: to write comments during executing. FALSE: to avoid comments
`

**Comment by muschellij2** [comment]
Does this run on R at the Terminal?

John

**Comment by VeroAra** [comment]
The code without "w = 1" runs on R at the Terminal.
`antsMotionCorr( list( d = 2 , a = regLABEL_LX, o = aimg ) ) # average img created to work as a reference
antsMotionCorr( list( d = 2 ,
                      o = list( mocoParams , mocoImg , aimg ) ,
                      m = list( name = "CC" , aimg , movingImage=regCONTROL_CX , metricWeight=1 , radius=1 , samplingStrategy="Regular", samplingPercentage=0.2 ) ,
                      t = "SyN[0.03, 3, 0]" , i = "1000x1000",
                      u = 1, e = 1 , s = "0x0", f = "2x1", n=1 ,
                      v = as.numeric(TRUE) )) #TRUE: to write comments during executing. FALSE: to avoid comments`
The code with "w=1" inside the antsMotionCorr does not run.
`antsMotionCorr( list( d = 2 , a = regLABEL_LX, o = aimg ) ) # average img created to work as a reference
antsMotionCorr( list( d = 2 ,
                      o = list( mocoParams , mocoImg , aimg ) ,
                      m = list( name = "CC" , aimg , movingImage=regCONTROL_CX , metricWeight=1 , radius=1 , samplingStrategy="Regular", samplingPercentage=0.2 ) ,
                      t = "SyN[0.03, 3, 0]" , i = "1000x1000",
                      u = 1, e = 1 , s = "0x0", f = "2x1", n=1 ,
                      v = as.numeric(TRUE),
 )) `

Thanks.

**Comment by VeroAra** [comment]
The code without "w=1" runs on R at the terminal, but it does not write out the displacement field.
`antsMotionCorr( list( d = 2 , a = regLABEL_LX, o = aimg ) ) # average img created to work as a reference
antsMotionCorr( list( d = 2 ,
                      o = list( mocoParams , mocoImg , aimg ) ,
                      m = list( name = "CC" , aimg , movingImage=regCONTROL_CX , metricWeight=1 , radius=1 , samplingStrategy="Regular", samplingPercentage=0.2 ) ,
                      t = "SyN[0.03, 3, 0]" , i = "1000x1000",
                      u = 1, e = 1 , s = "0x0", f = "2x1", n=1 ,
                      v = as.numeric(TRUE) ))`

The code with "w=1" does not run in R at the terminal.
`antsMotionCorr( list( d = 2 , a = regLABEL_LX, o = aimg ) ) # average img created to work as a reference
antsMotionCorr( list( d = 2 ,
                      o = list( mocoParams , mocoImg , aimg ) ,
                      m = list( name = "CC" , aimg , movingImage=regCONTROL_CX , metricWeight=1 , radius=1 , samplingStrategy="Regular", samplingPercentage=0.2 ) ,
                      t = "SyN[0.03, 3, 0]" , i = "1000x1000",
                      u = 1, e = 1 , s = "0x0", f = "2x1", n=1 ,
                      v = as.numeric(TRUE),
		      w = 1))`

Thank you.

**Comment by stnava** [comment]
i dont think that option is supported by the antsr wrapper.  one would have
to check the original c++ implementation to see why it would / would not
work but i suspect would be something easy to fix within ants.

however, you can easily do motion correction by splitting and merging the
time series via splitNDImageToList and mergeListToNDImage.  and use
whatever transform you like on each pairwise image.


brian

**Comment by stnava** [comment]
see https://github.com/ANTsX/ANTsR/wiki/nonrigid-motion-correction-example


brian
