### ISSUE TITLE
Pandoc error with devtools::check()

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsR#192]
I'm trying to run devtools::check() on some updated code, and I'm getting this error with the ANTsR.Rmd (which I have not modified). I am running devtools 1.13.3 and pandoc 2.0.0.1.

devtools::check()
Updating ANTsR documentation
Loading ANTsR
Setting env vars -----------------------------------------------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building ANTsR -------------------------------------------------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  build '/Users/pcook/code/ANTsR' --no-resave-data --no-manual 

* checking for file ‘/Users/pcook/code/ANTsR/DESCRIPTION’ ... OK
* preparing ‘ANTsR’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to build vignettes
* creating vignettes ... ERROR
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
Error: processing vignette 'ANTsR.Rmd' failed with diagnostics:
pandoc document conversion failed with error 2
Execution halted
Error: Command failed (1)

**Comment by muschellij2** [comment]
Please see https://github.com/rstudio/rmarkdown/issues/1120
Recommend solution: install new markdown as pandoc 2 is out:

devtools::install_github("rstudio/rmarkdown")


John

**Comment by cookpa** [comment]
Thanks! That got it
