### ISSUE TITLE
plot() does not output overlay with png() 

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTsR#195]
plot(image, mask) works as intended

pdf()
plot(image, mask)
dev.off() works as intended

png()
plot(image, mask)
dev.off() 
does not save the overlay, only outputs the image.

**Comment by dorianps** [comment]
I am even surprised that works already with your commands above. The only
way I know it works well is by specifying the output argument to the
png/jpg filename.

**Comment by muratmaga** [comment]
Actually, I can’t find any documentation on how to use the plot.antsImage() command anymore. That’s why I am looking into other output devices. ?plot doesn’t bring ANTsR specific options.
plot(image, output, output=’test.jpg’) doesn’t do anything. Or filename.
What is the correct parameter to specify?



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by stnava** [comment]
```
?plot.antsImage
```

not sure why `?plot.*` does not show `plot.antsImage` .... must be some tag that we failed to set.  if anyone knows, please chime in.
