### ISSUE TITLE
antsRegistration

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTsR#200]
Hi, 
I am trying to figure out how to pass smoothing and shrink factors to antsRegistration? This fails 

test=antsRegistration(moving=mi, fixed=fi,verbose=T, typeofTransform='SyN', list( s="3x2x1x0", f="4x3x2x1") )
All_Command_lines_OK
Using single precision for computations.
Exception Object caught: 

itk::ExceptionObject (0x5788bd0)
Location: "unknown" 
File: /root/antsr-install/ANTsRCore/src/ants/Utilities/antsCommandLineParser.h
Line: 126
Description: itk::ERROR: CommandLineParser(0x9dd01f0): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert '4x3x2x1' to type 'b' as Unmapped Type

I tried to modified this snippet, but I am wondering if it is not possible to mix simplified mode with full mode?
for simplified mode: 
 antsRegistration( fixed , moving , typeofTransform = c("Rigid","Affine","AffineFast","SyN","SyNCC"),  outputPrefix="./antsRegOut" 
For full mode: use standard ants call , e.g. : 
 ANTsR::antsRegistration( list( d=2,m="mi[r16slice.nii.gz,r64slice.nii.gz,1,20,Regular,0.05]", t="affine[1.0]", c="2100x1200x1200x0",  s="3x2x1x0", f="4x3x2x1", u="1", o="[xtest,xtest.nii.gz,xtest_inv.nii.gz]" ) )
full help:

**Comment by stnava** [comment]
hi murat

the smoothing sigmas are set automatically based on the iterations you set:

see https://github.com/ANTsX/ANTsRCore/blob/master/R/antsRegistration.R#L195-L199

also see 
https://github.com/ANTsX/ANTsRCore/blob/master/R/antsRegistration.R#L284-L294

for how to construct the argument list.   not sure this approach still works but it might.
