### ISSUE TITLE
lack of .mat output in linear only registration options

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTsR#201]
fi <- antsImageRead(getANTsRData("r16") )
mi <- antsImageRead(getANTsRData("r64") )
reg=antsRegistration(fi, mi, 'Rigid') #no $fwdtransform or $invtransform field in reg
reg=antsRegistration(fi, mi, 'SyN') #this is fine

This is with:
> antsVersions
  Dependency                                   GitTag
1       ANTs 18506d4b305e7abd33c435ecaf7dc3f0672cca72
2  ANTsRCore 6beaba2228e1a2cfd7e0d9ca8edeaf238824f6fd

**Comment by stnava** [comment]
i believe this would be fixed by updating antsrcore


brian

**Comment by muratmaga** [comment]
ok. will try.
