### ISSUE TITLE
Evaluate antsMotionCorr registration

### ISSUE THREAD

**Issue by VeroAra** [ANTsX/ANTsR#203]
With antsMotionCorr command I am able to obtain the mocoParameters (with the metricPost value) and the registered image. Is it also possible to see which has been the convergence criteria (number of iterations, metric value,...) during the registration?

I would also like to know which is the interpolation method that is being used. 

This are my command line results after the registration:
> `Registration using 1 total stages.
nimagestoavg 1
Stage 1
fixed image: 0x5af07a0
moving image: 0x5ddb560
number of levels = 2
shrink factors per level: [2, 1]
smoothing sigmas per level: [0, 0]
using fixed reference image for all frames 
regular sampling (percentage = 0.2)
using the CC metric (radius = 1).
employing scales estimator 
SyN iterations:1000 1000 
done resampling timepoint : 0
motion corrected out 0x5a2b760
i^th value 0  is -0.745147
write average post 0x5af07a0

> Total
 elapsed time: 10.3301 averagemetric -0.745147
get motion corr params 0x422aa90
motion-correction params written`

**Comment by stnava** [comment]
see `?antsrMetric` for similarity metric computations

see also `?antsrMotionCalculation` and `?antsMotionCalculation`

which have verbose options.
