### ISSUE TITLE
Wrong bounding box ordering in LabelGeometryMeasures

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsR#220]
In ``LabelGeometryMeasures`` I had labeled the bounding box elements incorrectly when writing the .csv file.  Specifically, I had originally coded (for 3-D) 

```
[x_lower, y_lower, z_lower, x_upper, y_upper, z_upper]
```

when it should've been 

```
[x_lower, x_upper, y_lower, y_upper, z_lower, z_upper]
```

One can see that when running the ANTsR ``labelGeometryMeasures`` example:

```
fi<-antsImageRead( getANTsRData("r16") , 2 )
seg<-kmeansSegmentation( fi, 3 )$segmentation
geom<-labelGeometryMeasures(seg,fi)
```

which produces

```
> geom[,grep( "BoundingBox", colnames( geom ) )]
  BoundingBoxLower_x BoundingBoxLower_y BoundingBoxUpper_x BoundingBoxUpper_y
1                 56                196                 43                213
2                 58                194                 45                211
3                 60                192                 49                210
```

Note that the ``Lower_x`` values are greater than the ``Upper_x`` values.

I [fixed](https://github.com/ANTsX/ANTs/commit/a89f1f4aa299518fc44589bb0b06a5ea818cc499#diff-fc6d233a37cb834ac0f4c0c1e196c5c4) that in the ANTs code.  Since this is just a wrapper, I'm assuming that simply updating the ANTs version should fix this bug.

**Comment by stnava** [comment]
antsr uses itkv5 stuff and currently produces:

```

  BoundingBoxLower_x BoundingBoxUpper_x BoundingBoxLower_y
BoundingBoxUpper_y

1                 56                196                 43
213

2                 58                194                 45
211

3                 60                192                 49
210
```

is that more like what you expect?


brian

**Comment by ntustison** [comment]
Awesome.  Looks like it's fixed then.  Great.
