### ISSUE TITLE
Minimum R version for ANTsR ?

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTsR#225]
Sometime ago the minimum requirement for ANTsR was R >=3.0. Now it looks like is just 2.10. Any idea on why/how we were able to relax the requirement? Is the 2.10 minimum requirement correct, has anybody actually tried to install it there?

**Comment by stnava** [comment]
It's probably 3.0

**Comment by dorianps** [comment]
[DESCRIPTION ](https://github.com/ANTsX/ANTsR/blob/master/DESCRIPTION#L25) should be updated then.

**Comment by muschellij2** [comment]
This has been updated in https://github.com/ANTsX/ANTsR/pull/221.  After merging, this can be closed.
