### ISSUE TITLE
just a question on current version

### ISSUE THREAD

**Issue by portokalh** [ANTsX/ANTsR#227]
From the Description file i see the current version being labeled 0.4.1 ?
I thought i had seen 0.7.2 previously. Any recommendation?
Thank you!

**Comment by muschellij2** [comment]
You can see in commit: https://github.com/ANTsX/ANTsR/commit/f8db4ece6cf8cadbdc0e8347bfb6e8c9114ee3a3 that it was changed.  Not my recommendation, but that should explain it.

**Comment by portokalh** [comment]
Thanks much, i have seen and i assume there must be reasons why this happened. I was wondering which way is best to go from here.

**Comment by muschellij2** [comment]
@stnava - this can be closed.

**Comment by stnava** [comment]
there was a typo in the version # that persisted for some time.

**Comment by portokalh** [comment]
got it, thanks!
