### ISSUE TITLE
Smoothing only in the z-direction

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTsR#230]
Manual lesion segmentation is typically performed on a single axis, i.e., slice by slice in axial view. This produces a jagged outline when seen from another view (i.e., sagittal). Smoothing and re-binarizing can help here, but I think the best ideal solution is to smooth only in the direction of labelling, i.e., axial. For example, tha gaussian should not be 3D but 2D, so the values affecting a single voxel are coming from below and above, but not from the sides.

Is there any way to do this with current ANTsR/ANTs tools (or with any other tool)?

Thanks

**Comment by muschellij2** [comment]
Loop through each slice, create image, smooth.

**Comment by stnava** [comment]
The help information below ---- read the part about sigma:



Smooth image


Description:


     Smooth image or multi-channel image


Usage:


     smoothImage(inimg, sigma, sigmaInPhysicalCoordinates = TRUE, FWHM =
FALSE,

       max_kernel_width = 70)



Arguments:


   inimg: Image to smooth


   sigma: Smoothing factor.  Can be scalar, in which case the same

          sigma is applied to each dimension, or a vector of length

          ‘dim(inimg)’ to specify a unique smoothness for each

          dimension.



brian

**Comment by stnava** [comment]
```
smoothImage( img, sigma = c(1,1,0) )
```

**Comment by dorianps** [comment]
Perfect, thanks.
