### ISSUE TITLE
Installing ANTsR onto Mac Sierra

### ISSUE THREAD

**Issue by Pandrews17** [ANTsX/ANTsR#231]
I am trying to install and adapt this program for a murine model but when I try to run sample data later on just to make sure the program works for human brain on my computer, I get lots of breakpoints. I tried uninstalling and reinstalling ANTsR but it comes up with a lot of errors in the installation processes. I have little to no coding experience but need to analyze fMRI data, so any help with installation and next steps would be much appreciated. Attached are screenshots from my RStudio window. Thanks!
<img width="780" alt="screen shot 2018-07-26 at 10 17 40 am" src="https://user-images.githubusercontent.com/41748469/43268810-8ea07832-90bf-11e8-8850-2715c5a354b7.png">
<img width="781" alt="screen shot 2018-07-26 at 10 17 49 am" src="https://user-images.githubusercontent.com/41748469/43268811-8eb3a3f8-90bf-11e8-81f4-8684489f1966.png">
<img width="745" alt="screen shot 2018-07-26 at 10 20 44 am" src="https://user-images.githubusercontent.com/41748469/43268812-8ec8ad48-90bf-11e8-9f02-03dc2dafd52e.png">
<img width="705" alt="screen shot 2018-07-26 at 10 21 00 am" src="https://user-images.githubusercontent.com/41748469/43268814-8eda6d4e-90bf-11e8-8027-b44728113516.png">
<img width="777" alt="screen shot 2018-07-26 at 10 21 18 am" src="https://user-images.githubusercontent.com/41748469/43268815-8eeae25a-90bf-11e8-92c7-6b2514d4e54b.png">
<img width="779" alt="screen shot 2018-07-26 at 10 21 29 am" src="https://user-images.githubusercontent.com/41748469/43268816-8f0915d6-90bf-11e8-891d-86487fa6144c.png">
<img width="780" alt="screen shot 2018-07-26 at 10 23 53 am" src="https://user-images.githubusercontent.com/41748469/43268817-8f1efc70-90bf-11e8-9b54-f3700a4d2535.png">
<img width="808" alt="screen shot 2018-07-26 at 10 28 57 am" src="https://user-images.githubusercontent.com/41748469/43268818-8f32c44e-90bf-11e8-97a8-d32776f858fe.png">
<img width="808" alt="screen shot 2018-07-26 at 10 29 34 am" src="https://user-images.githubusercontent.com/41748469/43268820-8f460388-90bf-11e8-9efd-db2121ba2e08.png">

**Comment by Pandrews17** [comment]
Thank you! I was able to install it, but as I try to run the code in (http://htmlpreview.github.io/?https://github.com/stnava/fMRIANTs/blob/master/ANTsRfMRI_FAQ.html) it says I don't have a package called RKRNS even though I downloaded and installed the package from GitHub. Is there something else I should be doing or a different preview of ANTsR I should be running to make sure it works?

**Comment by stnava** [comment]
try some google searches:

https://www.google.com/search?ei=NidaW6vxLqPCjwTXppNQ&q=github+antsr+fmri&oq=github+antsr+fmri&gs_l=psy-ab.3..0i71k1l8.0.0.0.17151.0.0.0.0.0.0.0.0..0.0....0...1..64.psy-ab..0.0.0....0.6q0HW1gYs3M

https://www.google.com/search?q=github+antsr+fmri&source=lnt&tbs=qdr:y&sa=X&ved=0ahUKEwiqu4OYxr3cAhUN24MKHdVUA48QpwUIIQ&biw=1338&bih=749

there is a good bit of content worth reading and comparing out there.  antsr provides many strategies and there are many opinions about how fmri processing should be done.  no single approach is correct for all data.   one should try to understand these and adapt to the problem at hand.   the vignettes on the antsr documentation page are always a good place to start.
