### ISSUE TITLE
mFilter no longer available

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsR#238]
https://cran.r-project.org/web/packages/mFilter/index.html

Package ‘mFilter’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2018-07-20 as check problems were not corrected despite reminders.

**Comment by stnava** [comment]
interesting.   i always hated mFilter anyway.    surely there are other options.

**Comment by muschellij2** [comment]
See https://github.com/mannau/h5#deprecation-notice for `h5`.  In PR #236 I have added `hdf5r` to a suggests rather than `h5` for the new version.  They have the same function names but I'm unsure as to whether the functions have exactly the same behavior and whether `writeNormalizedPopulationData` and `readNormalizedPopulationData` will work accordingly.

**Comment by muschellij2** [comment]
Same thing with https://cran.r-project.org/web/packages/rflann/index.html
