### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by portokalh** [ANTsX/ANTsR#239]
it looks like sparseDecom2 outputs
for nvecs=1 :      dim(sparseDecom2output$eig1)   as    [1 number_of_elements]
for nvecs>1 :      dim(sparseDecom2output$eig1)   as    [number_of_elements nvecs]
1. is it wrong to just use nvec=1?

2. i have seen in some examples that sparseness was set to negative values, but do not remember what this means.

thanks much for the clarifications!

Alex

**Comment by stnava** [comment]
1.    that would be very similar to  "sparse regression" - no wrong or right to it , just a matter of what you want to do

2.  positivity constraints are enforced by positive sparseness.   negative sparseness allows weight values that are both positive and negative
