### ISSUE TITLE
Error when installing ANTsR and extrantsr

### ISSUE THREAD

**Issue by JMMaronge** [ANTsX/ANTsR#241]
I am currently running R 3.5.1 on macOS 10.13.6

When I install the newest version of ANTsR using devtools with newest versions of cmaker and ITKR like so:

```
library( devtools )
install_github("stnava/cmaker")
install_github("stnava/ITKR")
install_github("stnava/ANTsR")
```

and then attempt:

```
install_github("muschellij2/extrantsr")
```
I receive the following error:

```
Error in namespaceExport(ns, exports) : 
  undefined exports: imageListToMatrix, imagesToMatrix, matrixToImages
ERROR: lazy loading failed for package ‘extrantsr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/extrantsr’
Installation failed: Command failed (1)
```

However, if I revert to version 0.4.0 of ANTsR:

```
install_github("stnava/ANTsR", ref="713a7b4")
install_github("muschellij2/extrantsr")
```

This works fine. Alternatively, if I run:

```
install_github("muschellij2/ANTsR")
install_github("muschellij2/extrantsr", upgrade_dependencies=FALSE)
```

This works as well.

Any suggestions?

@muschellij2 this is in regards to our conversation

**Comment by muschellij2** [comment]
Need to install the new version of ANTsR - then this should be closed comment.

**Comment by JMMaronge** [comment]
Just checked this and confirmed! Closing issue now. Thanks @muschellij2.
