### ISSUE TITLE
Travis fails for external package that relies on ANTsR

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTsR#242]
I relied on a script built by @muschellij2 to preload ANTsR and test LESYMAP on Travis. It worked until a couple of months ago, and now it's failing. Has anything changed on the method to test packages that depend on ANTsR?

LESYMAP travis script:
https://github.com/dorianps/LESYMAP/blob/master/.travis.yml

Error in Travis:
https://travis-ci.org/dorianps/LESYMAP/jobs/449529957
```
The command "Rscript -e 'devtools::session_info(installed.packages()[, "Package"])'" failed and exited with 1 during .
```

**Comment by muschellij2** [comment]
That is
https://gist.githubusercontent.com/muschellij2/183aca6ea4d326db549cdcc28e1ff395/raw/
is pretty old.

No idea of why the errors are there.  Tried some fixed and try again

Maybe `
John

**Comment by muschellij2** [comment]
Also @stnava, ANTsR hasn't had a tagged release in a long time.
John

**Comment by muschellij2** [comment]
@stnava @dorianps - this can be closed -correct?

**Comment by dorianps** [comment]
Yes, thank you for fixing. Closing.
