### ISSUE TITLE
Feature request: Include filename as a tag in antsImage

### ISSUE THREAD

**Issue by SlicerMorph** [ANTsX/ANTsR#253]
It would be nice if antsImageRead passes the filename used as a filename tag to the variable that contain the image.

**Comment by muschellij2** [comment]
Please provide example.  

Do you mean provide an attribute on the output antsImage object that contained the filename of the original image?  If so, what do you suggest when an image is copied?

If not, I don't understand the question.

**Comment by SlicerMorph** [comment]
Hi John,

> fn <- getANTsRData( "r16" )
> img<- antsImageRead( fn )
> img
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 256x256 
  Voxel Spacing       : 1x1 
  Origin              : 0 0 
  Direction           : 1 0 0 1 
if img if created through antsImageRead, then I want something like 
img$filename to return the filename specified. 

If img is created by say antsImageClone or by assignment than this can be set to NULL. 

I don't know this would be possible at all, but it will make working with multiple image lists a bit more convenient, as they will contain the filename they refer to.... It is just nice to have feature.

**Comment by dorianps** [comment]
This would be a good feature also for running antsImageWrite(img) with no
need to specify the filename, provided the user doesn't make mistakes in
overwriting processed files.
