### ISSUE TITLE
Iterative Update of Registration

### ISSUE THREAD

**Issue by suppechasper** [ANTsX/ANTsR#256]
Hi,

Very nice to have ANTs in R. 

Is it possible in antsRegistration to update the transforms in an iterative fashion? I.e:
1. Register X to Y1
2. Register X to Y2 starting form the previous transforms, and updating the previous transforms.

Thanks
Sam

**Comment by muratmaga** [comment]
You can do something like this

reg1 = antsRegistration(X, Y1, typeofTransform='SyN')
reg2 = antsRegistration(X, Y2, initialTransform = reg1$fwdtransforms, typeofTransform='SyN')

I am not sure how meaningful this would be if Y1 and Y2 are different images.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by suppechasper** [comment]
I think this is not quite what I want. I believe this concatenated two transformations. I'd like to update the original transforms and avoid finding an indirect path of transforms and also less regularized final transform. Of course I can just compute a new transform to Y2 from X but Y2 is an update of Y1 and the hope is that it would converge quicker when starting from the previous transform.

**Comment by muschellij2** [comment]
What about using `initialTransform`: transforms to prepend, in `antsRegistration`?
