### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by amirzolal** [ANTsX/ANTsR#259]
Hello, 

my attemtps at installation end with the following errors:

invariantImageSimilarity.cpp:209:40: error: ‘vnl_math_abs’ was not declared in this scope
     if ( vnl_math_abs( bestscale - 1.0 ) < 1.e-6 )
                                        ^
invariantImageSimilarity.cpp:222:47: error: ‘vcl_pow’ was not declared in this scope
       bestscale = vcl_pow( bestscale , powlev );
                                               ^

followed somwhat further by 

make: *** [invariantImageSimilarity.o] Error 1
ERROR: compilation failed for package ‘ANTsR’
* removing ‘/data/AA_Work/R/x86_64-redhat-linux-gnu-library/3.5/ANTsR’

**Comment by ntustison** [comment]
Yes, this issue is known and is addressed by this [pull request](https://github.com/ANTsX/ANTsR/pull/258).  

Hey @stnava , have you been able to take a look at this yet?
