### ISSUE TITLE
ANTsRCore installation

### ISSUE THREAD

**Issue by orangepasties** [ANTsX/ANTsR#261]
After installing ITKR using the binary method I get the following error when installing ANTsRCore:

[root@server tmp]# R CMD INSTALL v0.6.3.2.tar.gz
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing to library ‘/usr/lib64/R/library’
* installing *source* package ‘ANTsRCore’ ...
linux-gnu 0
fatal: Not a git repository (or any of the parent directories): .git
Cloning into 'ants'...
remote: Enumerating objects: 244, done.
remote: Counting objects: 100% (244/244), done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 22892 (delta 133), reused 139 (delta 102), pack-reused 22648
Receiving objects: 100% (22892/22892), 20.13 MiB | 15.35 MiB/s, done.
Resolving deltas: 100% (16089/16089), done.
Already on 'master'
Already up-to-date.
Note: checking out '9f6ab8f4225d52961246a70192775a53088951dc'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 9f6ab8f... PERF: itk n4 performance improvements
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test C_HAS_WARNING-Wno-uninitialized
-- Performing Test C_HAS_WARNING-Wno-uninitialized - Success
-- Performing Test C_HAS_WARNING-Wno-unused-parameter
-- Performing Test C_HAS_WARNING-Wno-unused-parameter - Success
-- Performing Test C_HAS_WARNING-Wall
-- Performing Test C_HAS_WARNING-Wall - Success
-- Performing Test C_HAS_WARNING-Wcast-align
-- Performing Test C_HAS_WARNING-Wcast-align - Success
-- Performing Test C_HAS_WARNING-Wdisabled-optimization
-- Performing Test C_HAS_WARNING-Wdisabled-optimization - Success
-- Performing Test C_HAS_WARNING-Wextra
-- Performing Test C_HAS_WARNING-Wextra - Success
-- Performing Test C_HAS_WARNING-Wformat=2
-- Performing Test C_HAS_WARNING-Wformat=2 - Success
-- Performing Test C_HAS_WARNING-Winvalid-pch
-- Performing Test C_HAS_WARNING-Winvalid-pch - Success
-- Performing Test C_HAS_WARNING-Wno-format-nonliteral
-- Performing Test C_HAS_WARNING-Wno-format-nonliteral - Success
-- Performing Test C_HAS_WARNING-Wpointer-arith
-- Performing Test C_HAS_WARNING-Wpointer-arith - Success
-- Performing Test C_HAS_WARNING-Wshadow
-- Performing Test C_HAS_WARNING-Wshadow - Success
-- Performing Test C_HAS_WARNING-Wunused
-- Performing Test C_HAS_WARNING-Wunused - Success
-- Performing Test C_HAS_WARNING-Wwrite-strings
-- Performing Test C_HAS_WARNING-Wwrite-strings - Success
-- Performing Test C_HAS_WARNING-funit-at-a-time
-- Performing Test C_HAS_WARNING-funit-at-a-time - Success
-- Performing Test C_HAS_WARNING-Wno-strict-overflow
-- Performing Test C_HAS_WARNING-Wno-strict-overflow - Success
-- Performing Test CXX_HAS_WARNING-Wall
-- Performing Test CXX_HAS_WARNING-Wall - Success
-- Performing Test CXX_HAS_WARNING-Wcast-align
-- Performing Test CXX_HAS_WARNING-Wcast-align - Success
-- Performing Test CXX_HAS_WARNING-Wdisabled-optimization
-- Performing Test CXX_HAS_WARNING-Wdisabled-optimization - Success
-- Performing Test CXX_HAS_WARNING-Wextra
-- Performing Test CXX_HAS_WARNING-Wextra - Success
-- Performing Test CXX_HAS_WARNING-Wformat=2
-- Performing Test CXX_HAS_WARNING-Wformat=2 - Success
-- Performing Test CXX_HAS_WARNING-Winvalid-pch
-- Performing Test CXX_HAS_WARNING-Winvalid-pch - Success
-- Performing Test CXX_HAS_WARNING-Wno-format-nonliteral
-- Performing Test CXX_HAS_WARNING-Wno-format-nonliteral - Success
-- Performing Test CXX_HAS_WARNING-Wpointer-arith
-- Performing Test CXX_HAS_WARNING-Wpointer-arith - Success
-- Performing Test CXX_HAS_WARNING-Wshadow
-- Performing Test CXX_HAS_WARNING-Wshadow - Success
-- Performing Test CXX_HAS_WARNING-Wunused
-- Performing Test CXX_HAS_WARNING-Wunused - Success
-- Performing Test CXX_HAS_WARNING-Wwrite-strings
-- Performing Test CXX_HAS_WARNING-Wwrite-strings - Success
-- Performing Test CXX_HAS_WARNING-funit-at-a-time
-- Performing Test CXX_HAS_WARNING-funit-at-a-time - Success
-- Performing Test CXX_HAS_WARNING-Wno-strict-overflow
-- Performing Test CXX_HAS_WARNING-Wno-strict-overflow - Success
-- Performing Test CXX_HAS_WARNING-Wno-deprecated
-- Performing Test CXX_HAS_WARNING-Wno-deprecated - Success
-- Performing Test CXX_HAS_WARNING-Wno-invalid-offsetof
-- Performing Test CXX_HAS_WARNING-Wno-invalid-offsetof - Success
-- Performing Test CXX_HAS_WARNING-Woverloaded-virtual
-- Performing Test CXX_HAS_WARNING-Woverloaded-virtual - Success
-- Performing Test CXX_HAS_WARNING-Wstrict-null-sentinel
-- Performing Test CXX_HAS_WARNING-Wstrict-null-sentinel - Success
-- Performing Test CXX_HAS_DISABLE_OPTIMIZATION_FLAG
-- Performing Test CXX_HAS_DISABLE_OPTIMIZATION_FLAG - Failed
-- Found Git: /usr/bin/git (found version "1.8.3.1")
-- SuperBuild - ANTS => Requires ITKv5,
-- SuperBuild -   ITKv5[OK]
-- SuperBuild - ANTS[OK]
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/RtmpE0O6lQ/R.INSTALL791143583eb/ANTsRCore-0.6.3.2/src/antb
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I/usr/lib64/R/library/ITKR/libs/include/ITK-5.0/ -I/tmp/RtmpE0O6lQ/R.INSTALL791143583eb/ANTsRCore-0.6.3.2/src -I/tmp/RtmpE0O6lQ/R.INSTALL791143583eb/ANTsRCore-0.6.3.2/src/ants/Examples/include/   -I/tmp/RtmpE0O6lQ/R.INSTALL791143583eb/ANTsRCore-0.6.3.2/src/ants/Utilities -I/tmp/RtmpE0O6lQ/R.INSTALL791143583eb/ANTsRCore-0.6.3.2/src/ants/Examples/ -I../inst/include/  -I/tmp/RtmpE0O6lQ/R.INSTALL791143583eb/ANTsRCore-0.6.3.2/src/ants/Tensor/  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/ITKR/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c Atropos.cpp -o Atropos.o
In file included from /usr/lib64/R/library/ITKR/libs/include/ITK-5.0/itkConfigure.h:22:0,
                 from /usr/lib64/R/library/ITKR/libs/include/ITK-5.0/itkMacro.h:42,
                 from /usr/lib64/R/library/ITKR/libs/include/ITK-5.0/itkLightObject.h:21,
                 from /usr/lib64/R/library/ITKR/libs/include/ITK-5.0/itkObject.h:31,
                 from /tmp/RtmpE0O6lQ/R.INSTALL791143583eb/ANTsRCore-0.6.3.2/src/ants/Utilities/itkSurfaceCurvatureBase.h:22,
                 from /tmp/RtmpE0O6lQ/R.INSTALL791143583eb/ANTsRCore-0.6.3.2/src/ants/Examples/include/ants.h:4,
                 from Atropos.cpp:5:
/usr/lib64/R/library/ITKR/libs/include/ITK-5.0/itk_compiler_detection.h:147:6: error: #error Unsupported compiler
 #    error Unsupported compiler
      ^
make: *** [Atropos.o] Error 1
ERROR: compilation failed for package ‘ANTsRCore’
* removing ‘/usr/lib64/R/library/ANTsRCore’

**Comment by stnava** [comment]
**Unsupported compiler** suggests your compiler is not compatible.
