### ISSUE TITLE
labelClusters producing wrong output

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTsR#263]
I use `labelClusters` to filter away small clusters from LESYMAP results. The function is supposed to return an image with each cluster found in the range `minThresh` to `maxThresh`. 

>Description:
>     This will give a unique ID to each connected component 1 through N
 >    of size > minClusterSize

It used to work before, it is used routinely in LESYMAP, but now it returns a map with 0 where the cluster should be and 1 everywhere else. This sort of inverted mask is not useful anymore, it removes the good cluster in the following example. 

Any idea what is going on?

To reproduce:
[temp.nii.gz](https://github.com/ANTsX/ANTsR/files/2959708/temp.nii.gz)
[tempclust.nii.gz](https://github.com/ANTsX/ANTsR/files/2959709/tempclust.nii.gz)
```
temp = antsImageRead('temp.nii.gz')
tempclust = labelClusters(abs(temp), minClusterSize = 150, minThresh = 0.099, maxThresh=1) 
```
Figure shows the mask returned by labelClusters in white, and the signal of the original image in red, which falls in the hole of the labelClusters mask.
![image](https://user-images.githubusercontent.com/9083517/54252816-a327a600-4522-11e9-9e9f-63e1bdc6bd11.png)

**Comment by stnava** [comment]
probably fixed with minor update to ants - meaning reinstall.

**Comment by dorianps** [comment]
Thanks @stnava, works now. Do you know how long has this bug been around?

**Comment by stnava** [comment]
i was not able to identify any clear issue.   it may be a compiler change
in handling of types or something like that.  so no.

brian
