### ISSUE TITLE
remove islands

### ISSUE THREAD

**Issue by 1alebra2** [ANTsX/ANTsR#267]
Hello everybody

Is there something like "remove islands" from a labelled image available? Or are there any workarounds?

any ideas are appreciated

alebra

**Comment by dorianps** [comment]
Define island, label or empty island?

**Comment by stnava** [comment]
he may be talking about filling holes .... in which case `iMath( img,
"FillHoles" ) ` where you may need to some other steps like thresholding
etc.

brian

**Comment by 1alebra2** [comment]
I meant how an island of a label of a specific size. 

> Am 01.04.2019 um 18:12 schrieb dorianps <notifications@github.com>:
> 
> Define island, label or empty island?
>

**Comment by muschellij2** [comment]
see ?labelClusters
John

**Comment by dorianps** [comment]
See here how I do it in a couple of lines, labelClusters with a threshold
can do it, then you multiply the binarized result with your original label
image to get rid of the small clisters:
https://github.com/dorianps/LESYMAP/blob/master/R/lsm_sccan.R#L233-L234
