### ISSUE TITLE
Contrast enhancement

### ISSUE THREAD

**Issue by 1alebra2** [ANTsX/ANTsR#269]
I need to increase the contrast (range) of MRI images. one way would be something like "histogram equalization". I did not find this . Did I miss thid or are there any other ways of doing this
thank you

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTsR/blob/master/R/histogramMatchImage.R

**Comment by ntustison** [comment]
Although, as @gdevenyi points out, we have histogram matching in ANTsR, we haven't yet ported ITK's [histogram equalization](https://itk.org/Doxygen/html/classitk_1_1AdaptiveHistogramEqualizationImageFilter.html) capabilities.  However, there are other R packages which do have such capabilities.  You might look at one of those as a possible solution.

**Comment by 1alebra2** [comment]
THanks to all

The histogram matching seems to be helpful

>>> Nick Tustison <notifications@github.com> schrieb am 11.04.2019 um 16:23:

Although, as @gdevenyi points out, we have histogram matching in ANTsR, we haven't yet ported ITK's histogram equalization capabilities. However, there are other R packages which do have such capabilities. You might look at one of those as a possible solution.
