### ISSUE TITLE
ANTsRCore, colormap and v8

### ISSUE THREAD

**Issue by nadluru** [ANTsX/ANTsR#270]
Dear ANTsR team,

I am trying to install ANTsR using `R CMD INSTALL` approach. I can get the ITKR installed from the source, ANTsRCore but only from binary (ANTsRCore_0.6.3.2_R_x86_64-pc-linux-gnu_R3.5.tar.gz) and then when I try to install ANTsR it says ANTsRCore could not be loaded because of missing colormap package which internally depends on v8 both of which I could get installed. I assumed if I installed ANTsRCore from binary I wouldn't have to install the colormap and v8 but that seems incorrect.

Overall the dependency on colormap and v8 seems to be main issue. Could you kindly advice on how best to proceed with the ANTsRCore installation?

The main error message from ANTsR installation is below.

>Error: package or namespace load failed for ‘ANTsRCore’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), v ersionCheck = vI[[j]]):                                                                                            there is no package called ‘colormap’                                                                            Error : package ‘ANTsRCore’ could not be loaded                                                                   ERROR: lazy loading failed for package ‘ANTsR’                                                                    * removing ‘/home/adluru/R/x86_64-redhat-linux-gnu-library/3.5/ANTsR’

Thank you so much for your help.
Sincerely,
Nagesh

**Comment by ntustison** [comment]
I personally find the ``devtools::install_github( "..." )`` route to be easiest for ITKR, ANTsRCore, and ANTsR.

**Comment by dorianps** [comment]
Just throwing it there, did you try installing V8-devel ?

**Comment by stnava** [comment]
reference this:   https://github.com/ANTsX/ANTsRCore/blob/master/.travis.yml

**Comment by nadluru** [comment]
Thank you all for your prompt suggestions. The main problem in any of the ways (including that from a binary) seems to be getting the V8 installed and loaded properly. I can't seem to be able to install the v8-devel without sudo. I am going to ask our IT to do it and report back how it goes. Thank you all again!

**Comment by stnava** [comment]
@muschellij2  has also suggested that the colormap / V8 dependency is not worth the pain it causes.   to resolve, someone would have to either:

* 1. refactor the dependency such that it is optional

and/or 

* 2.  refactor plot.antsImage st we can still use interesting colormaps pretty easily w/o requiring v8

**Comment by nadluru** [comment]
Dear team,

Sorry for the delay in my update. So our IT said it got the v8 and v8-devel installed. I can rpm query them (screenshot below).
![v8installed](https://user-images.githubusercontent.com/5951009/56507577-6074c880-64e7-11e9-8411-4f282b42a2cc.png)

I also added /usr/lib64 to LD_LIBRARY_PATH. In my rpm query I could not find /usr/include/v8-3.14 though which I see in the error message (screenshot below) when I tried to install ANTsRCore using

`devtools::install_github('stnava/ANTsRCore', lib='/home/adluru/R/x86_64-redhat-linux-gnu-library/3.5/')`

![v8error](https://user-images.githubusercontent.com/5951009/56507643-9154fd80-64e7-11e9-8b2a-3a536afa66a1.png)

What would be your recommendation be for next trials in getting the ANTsRCore installed on our servers. I see the previous comment was potentially to make v8 optional. Would it be easy enough for you to do this?

Thanks again for all your help and apologies for the delay in getting the update posted (weekends are not what they used to be for me in my early days of research).

Sincerely,
Nagesh

**Comment by muschellij2** [comment]
This is something to bring up to https://github.com/jeroen/V8
John

**Comment by muschellij2** [comment]
Also - likely something in LD_LIBRARY_PATH or other paths.
John

**Comment by muschellij2** [comment]
Try simply install.packages("V8") and see the same result.
John

**Comment by nadluru** [comment]
>This is something to bring up to https://github.com/jeroen/V8
John

I just submitted an issue [there](https://github.com/jeroen/V8/issues/60) as well.

> Also - likely something in LD_LIBRARY_PATH or other paths.
John

I did update LD_LIBRARY_PATH to include /usr/lib64 which is where the v8 libraries seem to have been installed (you can see that from the first screenshot in my previous comment).

>Try simply install.packages("V8") and see the same result.
John

Same result with the same error message!

**Comment by hassaanmahmood** [comment]
@nadluru
hi,
      did you solve your problem? I am also getting same error 
sudo R CMD INSTALL ANTsRCore
* installing to library ‘/home/hassan/R/x86_64-pc-linux-gnu-library/3.4’
ERROR: dependency ‘colormap’ is not available for package ‘ANTsRCore’

thanks

**Comment by hassaanmahmood** [comment]
I solved this issue by doing this

sudo apt-get install libcurl4-openssl-dev libssl-dev
if(!require("V8")) install.packages("V8")
if(!require("devtools")) install.packages("devtools")
devtools::install_github("bhaskarvk/colormap")
sudo R CMD INSTALL ANTsRCore

**Comment by nadluru** [comment]
@hassaanmahmood 
Thanks for reporting your solution, but I am not sure if this will work for RHEL 7. I don't have sudo privileges to test this myself and I will bring it up with our IT.

**Comment by stnava** [comment]
I removed the dependency on colormap/V8 with a recent commit.  fewer colormap options but still several good options via viridis.
