### ISSUE TITLE
SLURM Errors

### ISSUE THREAD

**Issue by hermeckerogg** [ANTsX/ANTsR#288]
Hi all.

I'm trying to build a subject-specific template for some pediatric timeseries data. 

antsMultivariateTemplateConstruction2.sh -d 4 -j 6 -k 1 -n 0 -r 1 -t SyN  -c 5 -o MY sub-M87192301_Session1_task-restopen_bold.nii.gz sub-M87192301_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restopen_bold.nii.gz

All of the timeseries are in a folder, but the slurm scripts being generated don't seem to look like slurm scripts and it looks like the variables are not passing either.

Same issue even when I submit it as a SLURM job.

Any advice would be appreciated.

Thanks in advance!

antsMultivariateTemplateConstruction2.sh -d 4 -j 6 -k 1 -n 0 -r 1 -t SyN  -c 5 -o MY sub-M87192301_Session1_task-restopen_bold.nii.gz sub-M87192301_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restopen_bold.nii.gz

[job_0_0_metriclog.txt](https://github.com/ANTsX/ANTsR/files/3860690/job_0_0_metriclog.txt)
[job_1_0_metriclog.txt](https://github.com/ANTsX/ANTsR/files/3860691/job_1_0_metriclog.txt)
[job_2_0_metriclog.txt](https://github.com/ANTsX/ANTsR/files/3860692/job_2_0_metriclog.txt)
[job_3_0_metriclog.txt](https://github.com/ANTsX/ANTsR/files/3860693/job_3_0_metriclog.txt)

[ANTs_Slurm_Error.zip](https://github.com/ANTsX/ANTsR/files/3860696/ANTs_Slurm_Error.zip)

--------------------------------------------------------------------------------------
 Creating template MYtemplate0.nii.gz from a population average image from the inputs.
   sub-M87192301_Session1_task-restopen_bold.nii.gz sub-M87192301_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restopen_bold.nii.gzpwd
--------------------------------------------------------------------------------------
/trdapps/linux-x86_64/bin/ants/bin/antsMultivariateTemplateConstruction2.sh: line 272: 223250 Segmentation fault      ${ANTSPATH}/AverageImages $dim $output 1 ${images[*]}
sbatch: error: Batch job submission failed: No partition specified or system default partition
sbatch: error: Batch job submission failed: No partition specified or system default partition
sbatch: error: Batch job submission failed: No partition specified or system default partition
^C
*** User pressed CTRL + C ***
\n*** Performing cleanup, please wait ***\n
killing:  223312
/trdapps/linux-x86_64/bin/ants/bin/antsMultivariateTemplateConstruction2.sh: line 448: kill: (223312) - No such process
[tderamus@trendscn001 Template_Maker]$ antsMultivariateTemplateConstruction2.sh -d 4 -j 6 -k 1 -n 0 -r 1 -t SyN  -c 5 -o MY sub-M87192301_Session1_task-restopen_bold.nii.gz sub-M87192301_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restopen_bold.nii.gz

--------------------------------------------------------------------------------------
 Creating template MYtemplate0.nii.gz from a population average image from the inputs.
   sub-M87192301_Session1_task-restopen_bold.nii.gz sub-M87192301_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restopen_bold.nii.gz
--------------------------------------------------------------------------------------
 bigimage 4 maxSize [82, 82, 56]
 Setting physcal space of output average image based on largest image
 Averaging 4 images with dim = 3 vector components 1
 reading sub-M87192301_Session1_task-restopen_bold.nii.gz
 reading sub-M87192301_Session1_task-restclosed_bold.nii.gz
 reading sub-M68290751_Session1_task-restclosed_bold.nii.gz
 reading sub-M68290751_Session1_task-restopen_bold.nii.gz
 writing output sbatch: error: Batch job submission failed: No partition specified or system default partition
sbatch: error: Batch job submission failed: No partition specified or system default partition
sbatch: error: Batch job submission failed: No partition specified or system default partition
sbatch: error: Batch job submission failed: No partition specified or system default partition

--------------------------------------------------------------------------------------
 Starting ANTS rigid registration on SLURM cluster. Submitted 4 jobs
--------------------------------------------------------------------------------------
  Waiting for 0 jobs:
  No more jobs in queue

/trdapps/linux-x86_64/bin/ants/bin/AverageImages 3 MYtemplate0.nii.gz 1 ./rigid0_0_sub-M87192301_Session1_task-restopen_bold.nii.gz ./rigid1_0_sub-M87192301_Session1_task-restclosed_bold.nii.gz ./rigid2_0_sub-M68290751_Session1_task-restclosed_bold.nii.gz ./rigid3_0_sub-M68290751_Session1_task-restopen_bold.nii.gz
/trdapps/linux-x86_64/bin/ants/bin/antsMultivariateTemplateConstruction2.sh: line 272: 223458 Segmentation fault      ${ANTSPATH}/AverageImages $dim $output 1 ${images[*]}

--------------------------------------------------------------------------------------
 Start to build templates: MYtemplate0.nii.gz
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
 Mapping parameters
--------------------------------------------------------------------------------------
 ANTSPATH is /trdapps/linux-x86_64/bin/ants/bin

 Dimensionality:           3
 Do N4 bias correction:    0
 Back up each iteration:   0
 Similarity metric:        CC
 Gradient step:            0.25
 Transformation:           SyN
 Max iterations:           100x100x70x20
 Smoothing factors:        3x2x1x0
 Shrink factors:           6x4x2x1
 Output prefix:            MY
 Template:                 MYtemplate
 Template update steps:    4
 Template population:      sub-M87192301_Session1_task-restopen_bold.nii.gz sub-M87192301_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restclosed_bold.nii.gz sub-M68290751_Session1_task-restopen_bold.nii.gz
 Number of modalities:     1
 Madality weights:
 Image statistic:          1
--------------------------------------------------------------------------------------
sbatch: error: Batch job submission failed: No partition specified or system default partition
sbatch: error: Batch job submission failed: No partition specified or system default partition
sbatch: error: Batch job submission failed: No partition specified or system default partition
sbatch: error: Batch job submission failed: No partition specified or system default partition

--------------------------------------------------------------------------------------
 Starting ANTS registration on SLURM cluster. Submitted 4 jobs
--------------------------------------------------------------------------------------
  Waiting for 0 jobs:
  No more jobs in queue

ls: cannot access MY*Warp.nii.gz: No such file or directory
ls: cannot access MY*GenericAffine.mat: No such file or directory
shapeupdatetotemplate()

--------------------------------------------------------------------------------------
 shapeupdatetotemplate---voxel-wise averaging of the warped images to the current template
Mon Nov 18 16:10:31 EST 2019
--------------------------------------------------------------------------------------
ls: cannot access MYtemplate0*WarpedToTemplate.nii.gz: No such file or directory
ERROR shapeupdatedtotemplate - imagelist length is 0

**Comment by ntustison** [comment]
Can you repost over at the ANTs/ANTs repo?

**Comment by hermeckerogg** [comment]
Of course. My apologies.

**Comment by hermeckerogg** [comment]
Done. Closing.
