### ISSUE TITLE
getSyMG function

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsR#297]
The function `getSyMG` is defined in 2 different places, depending on the `normalize` flag:
https://github.com/ANTsX/ANTsR/blob/master/R/multiscaleSVDxpts.R#L3155
https://github.com/ANTsX/ANTsR/blob/master/R/multiscaleSVDxpts.R#L3139

The issue is that the line that calls `getSyMG` only uses the first function arguments:
https://github.com/ANTsX/ANTsR/blob/master/R/multiscaleSVDxpts.R#L3241
so if we ever use `energyType = "normalized"` in `symlr`, I believe this will fail:

**Comment by stnava** [comment]
am working  on this - hoping to finish up today.
