### ISSUE TITLE
Build time due to possibly extraneous programs

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsR#308]
Hey @stnava ,

One thing I noticed with the recent [pull request](https://github.com/ANTsX/ANTsR/pull/307) was that the programs ``confidenceConnectedImage.cpp`` and ``connectedThresholdImage.cpp`` are getting compiled but they're [not included](https://github.com/ANTsX/ANTsR/blob/master/src/init.c#L17-L18) in the list of ANTsR programs.  They look familiar like maybe I wrote them but I haven't used them and they're obviously not being used in ANTsR and they're just increasing build times.  Anyway, what do you think about getting rid of them to reduce the build time?

**Comment by stnava** [comment]
sounds reasonable - they can always be pulled back in if need be.
