### ISSUE TITLE
Travis failure for ANTsR/LINDA/LESYMAP ?

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTsR#313]
**Describe the bug**
Travis is failing for my downstream packages [LESYMAP](https://travis-ci.org/dorianps/LESYMAP)/[LINDA](https://travis-ci.org/dorianps/LINDA). I am trying to find out why, but the log is not telling much at first glance:
https://api.travis-ci.org/v3/job/683673823/log.txt . Looks like ANTsR/Core binaries are being installed but not seen. Looks also like ANTsR has its own problems with [failing on Travis](https://travis-ci.org/ANTsX/ANTsR).

Any idea how to fix the issues? My [travis script](https://github.com/dorianps/LESYMAP/blob/master/.travis.yml) relies on http://bit.ly/antsr_travis_sh maintained by @muschellij2.

**To Reproduce**
NA

**Expected behavior**
Travis pass.

**Screenshots**

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
ANTsR was successful on Travis until 3 weeks ago. Note also, official release version of R is now 4.0.0, not 3.* anymore.

**Comment by dorianps** [comment]
Both links above are failed build though. Not sure I follow the logic.  Btw, trusty used to be fine for months, these failures have emerged more recently.

**Comment by stnava** [comment]
recent failures have to do with some work done by @ntustison which requires updated ITK ANTs etc - ie new releases.   will get around to eventually.

**Comment by ntustison** [comment]
I believe I addressed that recent work (simulated displacement fields) when I updated the git tag in ANTsRCore [here](https://github.com/ANTsX/ANTsRCore/commit/b694fa97c2727562131a9231fac312899bd3b033).  Could that be a cache issue?

**Comment by dorianps** [comment]
Is that affecting the compiled builds used in Travis for downstream packages like lesymap, which seem to be hosted in  neuroconductor? Maybe @muschellij2 knows the answer to this.

```
Installing ANTsRCore package binaries
--2020-05-06 04:11:45--  https://github.com/neuroconductor/ANTsRCore/releases/download/0.7.4.nc4080/ANTsRCore_0.7.4_R_x86_64-pc-linux-gnu_R3.6.tar.gz
Resolving github.com (github.com)... 140.82.112.3
```

**Comment by stnava** [comment]
@ntustison did we update the releases?  if not then that's one issue ... a 2nd could require cache clearing

**Comment by ntustison** [comment]
Oh, then yeah, I didn't ever do anything with releases so then that would be a problem.

**Comment by muschellij2** [comment]
So it depends on what you're pulling from - either neuroc or the ANTsR
repo.  If this doesn't work with Neuroc version, then need to update the
neuroc version by new submission
Best,
John

**Comment by dorianps** [comment]
@muschellij2  I just rely on your script to get ANTsR/Core on travis before installing lesymap/linda, and that gets the binaries from neurocnductor. That is usually sufficient, but I am always of the idea that the script that install ANTsR from binaries for travis testing should be a feature ANTsR has itself in the repository. Unfortunately, I can't contribute with something like it anytime soon, just putting out a thought for the other devs.

**Comment by stnava** [comment]
probably resolved as of the numerous commits this morning --- but still waiting to see

**Comment by stnava** [comment]
@ntustison @dorianps looks like we are good now re: antsrnet linda etc ... pls close if you agree

**Comment by dorianps** [comment]
Thanks @stnava . On my packages I still have failures, but it might be because of neuroconductor being behind. Can you please push a commit with the word `submit_package_release` in it so Neuroconductor picks it up automatically?

**Comment by ntustison** [comment]
Thanks @stnava.  ANTsRNet is now green.

**Comment by dorianps** [comment]
Had to switch to Xenial for linux to go green, but it works now. Closing.

I suggest someone pushes an empty commit with `submit_package_release` for neuroconductor to pick up the new release.
