### ISSUE TITLE
details on getTemplateCoordinates, and ANTsR Data (mni, mnia, mnib)

### ISSUE THREAD

**Issue by ptsii** [ANTsX/ANTsR#320]
I'd like to use getTemplateCoordinates to assign coordinates to some data for a publication. Where can I get info on what getTemplateCoordinates is doing, and how mnia and mnib were created.  I assume that getTemplateCoordinates takes my stat image, registers mni to it, then uses the mapping to assess where my stat blobs (I created with labelClusters) fall into mnia and mnib?  I take it (but want to be sure) that even though my stats image and mni have very different values, that ANTsR registration does the right thing?  Any details appreciated!

**Comment by stnava** [comment]
the MNI image is from Mindboggle.  recent discussion here:

https://www.biorxiv.org/content/10.1101/2019.12.19.883330v1.full.pdf

`mnia` is AAL labels https://en.wikipedia.org/wiki/Automated_Anatomical_Labeling

`mnib` is Brodmann labels 

more on all this here https://people.cas.sc.edu/rorden/mricro/lesion.html#brod
