### ISSUE TITLE
Installing issue - OS Catalina 10.15.7

### ISSUE THREAD

**Issue by Georgina85** [ANTsX/ANTsR#330]
Hello, I am trying to install LESYMAP. I use OS Catalina 10.15.7 and I am having the following issue when trying to install ANTsR:

 (converted from warning) installation of package ‘/var/folders/96/xd970zqj45xcq6zzyccv0jrw0000gn/T//RtmpuACDzr/filee1333d67fed8/ANTsRCore_0.7.4.8.tar.gz’ had non-zero exit status

Could someone help me to resolve it?
Thank you in advance,
Georgina

**Comment by jefferis** [comment]
Hello @Georgina85, I'm just a user, not a dev, but I'm afraid you'll need to provide some more detailed error messages to help them debug that install issue. Best, Greg.

**Comment by Georgina85** [comment]
Hello @jefferis, thank you for your reply. This is the full error, I don't know if it is more helpful:
* installing *source* package ‘ANTsRCore’ ...
** using staged installation
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
darwin19 1
fatal: not a git repository (or any of the parent directories): .git
Cloning into 'ants'...
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Note: switching to '5b7c090b0dd8f911b013b374a06177fc0ac5c60e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5b7c090b BUG: revert last change - just build a function directly in R
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Not using CCache
-- Performing Test C_HAS_WARNING-Wno-uninitialized
-- Performing Test C_HAS_WARNING-Wno-uninitialized - Success
-- Performing Test C_HAS_WARNING-Wno-unused-parameter
-- Performing Test C_HAS_WARNING-Wno-unused-parameter - Success
-- Performing Test C_HAS_WARNING-Wall
-- Performing Test C_HAS_WARNING-Wall - Success
-- Performing Test C_HAS_WARNING-Wno-long-double
-- Performing Test C_HAS_WARNING-Wno-long-double - Failed
-- Performing Test C_HAS_WARNING-Wcast-align
-- Performing Test C_HAS_WARNING-Wcast-align - Success
-- Performing Test C_HAS_WARNING-Wdisabled-optimization
-- Performing Test C_HAS_WARNING-Wdisabled-optimization - Success
-- Performing Test C_HAS_WARNING-Wextra
-- Performing Test C_HAS_WARNING-Wextra - Success
-- Performing Test C_HAS_WARNING-Wformat_2
-- Performing Test C_HAS_WARNING-Wformat_2 - Success
-- Performing Test C_HAS_WARNING-Winvalid-pch
-- Performing Test C_HAS_WARNING-Winvalid-pch - Success
-- Performing Test C_HAS_WARNING-Wno-format-nonliteral
-- Performing Test C_HAS_WARNING-Wno-format-nonliteral - Success
-- Performing Test C_HAS_WARNING-Wpointer-arith
-- Performing Test C_HAS_WARNING-Wpointer-arith - Success
-- Performing Test C_HAS_WARNING-Wshadow
-- Performing Test C_HAS_WARNING-Wshadow - Success
-- Performing Test C_HAS_WARNING-Wunused
-- Performing Test C_HAS_WARNING-Wunused - Success
-- Performing Test C_HAS_WARNING-Wwrite-strings
-- Performing Test C_HAS_WARNING-Wwrite-strings - Success
-- Performing Test C_HAS_WARNING-funit-at-a-time
-- Performing Test C_HAS_WARNING-funit-at-a-time - Success
-- Performing Test C_HAS_WARNING-Wno-strict-overflow
-- Performing Test C_HAS_WARNING-Wno-strict-overflow - Success
-- Performing Test CXX_HAS_WARNING-Wall
-- Performing Test CXX_HAS_WARNING-Wall - Success
-- Performing Test CXX_HAS_WARNING-Wno-long-double
-- Performing Test CXX_HAS_WARNING-Wno-long-double - Failed
-- Performing Test CXX_HAS_WARNING-Wcast-align
-- Performing Test CXX_HAS_WARNING-Wcast-align - Success
-- Performing Test CXX_HAS_WARNING-Wdisabled-optimization
-- Performing Test CXX_HAS_WARNING-Wdisabled-optimization - Success
-- Performing Test CXX_HAS_WARNING-Wextra
-- Performing Test CXX_HAS_WARNING-Wextra - Success
-- Performing Test CXX_HAS_WARNING-Wformat_2
-- Performing Test CXX_HAS_WARNING-Wformat_2 - Success
-- Performing Test CXX_HAS_WARNING-Winvalid-pch
-- Performing Test CXX_HAS_WARNING-Winvalid-pch - Success
-- Performing Test CXX_HAS_WARNING-Wno-format-nonliteral
-- Performing Test CXX_HAS_WARNING-Wno-format-nonliteral - Success
-- Performing Test CXX_HAS_WARNING-Wpointer-arith
-- Performing Test CXX_HAS_WARNING-Wpointer-arith - Success
-- Performing Test CXX_HAS_WARNING-Wshadow
-- Performing Test CXX_HAS_WARNING-Wshadow - Success
-- Performing Test CXX_HAS_WARNING-Wunused
-- Performing Test CXX_HAS_WARNING-Wunused - Success
-- Performing Test CXX_HAS_WARNING-Wwrite-strings
-- Performing Test CXX_HAS_WARNING-Wwrite-strings - Success
-- Performing Test CXX_HAS_WARNING-funit-at-a-time
-- Performing Test CXX_HAS_WARNING-funit-at-a-time - Success
-- Performing Test CXX_HAS_WARNING-Wno-strict-overflow
-- Performing Test CXX_HAS_WARNING-Wno-strict-overflow - Success
-- Performing Test CXX_HAS_WARNING-Wno-deprecated
-- Performing Test CXX_HAS_WARNING-Wno-deprecated - Success
-- Performing Test CXX_HAS_WARNING-Wno-invalid-offsetof
-- Performing Test CXX_HAS_WARNING-Wno-invalid-offsetof - Success
-- Performing Test CXX_HAS_WARNING-Wno-undefined-var-template
-- Performing Test CXX_HAS_WARNING-Wno-undefined-var-template - Success
-- Performing Test CXX_HAS_WARNING-Woverloaded-virtual
-- Performing Test CXX_HAS_WARNING-Woverloaded-virtual - Success
-- Performing Test CXX_HAS_WARNING-Wstrict-null-sentinel
-- Performing Test CXX_HAS_WARNING-Wstrict-null-sentinel - Failed
-- Performing Test C_HAS_WARNING-mtune_native
-- Performing Test C_HAS_WARNING-mtune_native - Success
-- Performing Test C_HAS_WARNING-march_corei7
-- Performing Test C_HAS_WARNING-march_corei7 - Success
-- Performing Test CXX_HAS_WARNING-mtune_native
-- Performing Test CXX_HAS_WARNING-mtune_native - Success
-- Performing Test CXX_HAS_WARNING-march_corei7
-- Performing Test CXX_HAS_WARNING-march_corei7 - Success
-- Found Git: /usr/bin/git (found version "2.24.1 (Apple Git-126)") 
-- SuperBuild - ANTS => Requires ITKv5, 
-- SuperBuild -   ITKv5[OK]
-- SuperBuild - ANTS[OK]
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    COPY_SCRIPT_FILES_TO_BIN_DIR


-- Build files have been written to: /private/var/folders/96/xd970zqj45xcq6zzyccv0jrw0000gn/T/RtmpBxxBLi/R.INSTALLe731111b1dc1/ANTsRCore/src/antb
** libs
/Users/georgina/.R/Makevars:2: *** missing separator.  Stop.
ERROR: compilation failed for package ‘ANTsRCore’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ANTsRCore’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ANTsRCore’
Error: Failed to install 'LESYMAP' from GitHub:
  Failed to install 'ANTsR' from GitHub:
  Failed to install 'ANTsRCore' from GitHub:
  (converted from warning) installation of package ‘/var/folders/96/xd970zqj45xcq6zzyccv0jrw0000gn/T//RtmpuACDzr/filee1333d67fed8/ANTsRCore_0.7.4.8.tar.gz’ had non-zero exit status

**Comment by jefferis** [comment]
it looks like there is an error in this file on your system which modifies R's compilation behaviour:

```
/Users/georgina/.R/Makevars:2: *** missing separator. Stop.
```

which is actually not part of of ANTsR. If you are not sure of the problem you could share it here. For example in terminal

```
cat /Users/georgina/.R/Makevars
```

**Comment by Georgina85** [comment]
Thanks again for your help!
Does that help:
 georgina$ cat /Users/georgina/.R/Makevars
FLIBS=-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0 -
L/usr/local/gfortran/lib -lgfortran -lquadmath -lm

**Comment by cookpa** [comment]
What was the install command?

**Comment by Georgina85** [comment]
library(devtools)
?install_github
devtools::session_info()
devtools::install_github('dorianps/LESYMAP')

The RStudio version is 1.3.1073

**Comment by jefferis** [comment]
Is this one line or two ?
```
FLIBS=-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0 -
L/usr/local/gfortran/lib -lgfortran -lquadmath -lm
```
I assume it should be one line (with a blank line following for pref)

**Comment by Georgina85** [comment]
Actually  it is two lines.

**Comment by jefferis** [comment]
> Actually  it is two lines.

So you need to edit it to make it one.

**Comment by cookpa** [comment]
Good call @jefferis

**Comment by Georgina85** [comment]
Thank you both for your replies, but I am kind of confused. The aforementioned command is the output when I typed 
cat /Users/georgina/.R/Makevars. 
When you suggest to edit it, you mean to run it as one command at the terminal?

**Comment by jefferis** [comment]
open -e /Users/georgina/.R/Makevars

to edit and fix

**Comment by cookpa** [comment]
Or from the command line

```
echo "FLIBS=-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm" > /Users/georgina/.R/Makevars
```

The quoted text should not contain any line breaks. Sometimes these get introduced by browsers / email clients, so watch out when you copy and paste.

**Comment by cookpa** [comment]
Or from the command line

```
echo 'FLIBS=-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm' > ~/.R/Makevars
```

There should be no line breaks in the above.

If this doesn't fix it, you might need other variables defined for Catalina. I'll find the other issue

**Comment by cookpa** [comment]
Here's the Makevars file I'm using

https://github.com/ANTsX/ANTsR/issues/291#issuecomment-564825846

**Comment by cookpa** [comment]
However I should add I've installed ANTsR on another machine with 10.15.6 without any problems, without doing anything to Makevars. I just installed XCode, then devtools, then ANTsR.

**Comment by Georgina85** [comment]
I have just corrected the script and installation was successful! @jefferis and @cookpa thank you once again for your time and help!!!

**Comment by cookpa** [comment]
Excellent, thanks for the update.
