### ISSUE TITLE
How to save indices of column in timeseries2matrix function

### ISSUE THREAD

**Issue by prateeksasan1** [ANTsX/ANTsR#335]
Hi,

I am trying to convert a 4-d image to a matrix using a mask using timeseries2matrix. I am also interested in noting what part of the mask corresponds to what column. Is it possible? 

For e.g 4-d image is of dimension 90*100*80*1200 (1200 is the time point)
and i have a 3-d binary mask (dim = 90*100*80) with sum(mask) = 150

The output of timeseries2matrix would be a matrix of size 1200 * 150. 

I want to know which indices of the mask the columns correspond to.   i.e 1st column is mask index (1, 4, 5) , 2nd is (1, 4, 6) etc. 

Is there an easy way to do this. I see in your code that you subset the image which makes it a vector and then turn it into a matrix but couldnt figure out how to get the indices

**Comment by stnava** [comment]
use antsGetNeighborhood* functionality with radius=0 .... read the
documentation

brian

**Comment by prateeksasan1** [comment]
Thanks. I was not aware of this function. 

Using getNeighborhoodInMask with spatial.info = TRUE, the 2nd matrix in the list gave me the indices. Awesome. Thanks a lot

Prateek Sasan
