### ISSUE TITLE
Fuzzy spatial c-means

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsR#339]
Hey @stnava,

In working on this histograms paper, I implemented a version of the fuzzy spatial c-means since I couldn't find it anywhere.  It's pretty quick

```
fuzzySpatialCMeansSegmentation <- function( image, mask, numberOfClusters = 4,
  m = 2, p = 1, q = 1, radius = 2, maxNumberOfIterations = 20, convergenceThreshold = 0.2,
  verbose = FALSE )
```

```
seg <- fuzzySpatialCMeansSegmentation( image, mask, numberOfClusters = 3, convergenceThreshold = 0.01, verbose = TRUE )
Cluster centers:  63.5 127 190.5 
Iteration 1 (out of 20) --- Dice overlap = 0
Iteration 2 (out of 20) --- Dice overlap = 0.8941908
Iteration 3 (out of 20) --- Dice overlap = 0.9218776
Iteration 4 (out of 20) --- Dice overlap = 0.9493425
Iteration 5 (out of 20) --- Dice overlap = 0.9635466
Iteration 6 (out of 20) --- Dice overlap = 0.9742551
Iteration 7 (out of 20) --- Dice overlap = 0.9824668
Iteration 8 (out of 20) --- Dice overlap = 0.9885702
Iteration 9 (out of 20) --- Dice overlap = 0.9902902
```

<img width="1491" alt="Screen Shot 2021-02-12 at 8 57 01 AM" src="https://user-images.githubusercontent.com/324811/107798045-784abb80-6d10-11eb-8d63-df6d3757219e.png">

Was wondering if it'd be worth having in ANTsR?

**Comment by stnava** [comment]
yes - I have a few implementations of this lying around as well but never added it ... probably worth having due to speed.

**Comment by ntustison** [comment]
Okay, will put that in.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsR/pull/341
