### ISSUE TITLE
Installation fails on Ubuntu 22.04LTS with R4.2.0

### ISSUE THREAD

**Issue by JPolzehl** [ANTsX/ANTsR#364]
R CMD build ANTsR  fails with errors on Ubuntu 22.04LTS with R4.2.0
ITK and ANTsRCore were successfully installed using git sources

$ git clone https://github.com/ANTsX/ANTsR
$ R CMD build ANTsR

* checking for file ‘ANTsR/DESCRIPTION’ ... OK
* preparing ‘ANTsR’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘ANTsR’ ...
** using staged installation
linux-gnu 0
** libs
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG -I/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/ -I/tmp/RtmpZGhikT/Rbuild79b92af2151d/ANTsR/src    -I/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/   -I../inst/include/  -I'/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/Rcpp/include' -I'/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/include' -I'/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include' -I/usr/local/include   -fpic  -g -O2  -c AddNoiseToImage.cpp -o AddNoiseToImage.o

...

/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkFixedArray.h:266:29: error: ‘constexpr const ValueType& itk::FixedArray<TValue, VLength>::operator[](unsigned int) const’ cannot be overloaded with ‘constexpr itk::FixedArray<TValue, VLength>::ValueType& itk::FixedArray<TValue, VLength>::operator[](unsigned int) const’
  266 |   constexpr const_reference operator[](unsigned int index) const { return m_InternalArray[index]; }
      |                             ^~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkFixedArray.h:265:29: note: previous declaration ‘constexpr itk::FixedArray<TValue, VLength>::ValueType& itk::FixedArray<TValue, VLength>::operator[](unsigned int) const’
  265 |   constexpr reference       operator[](unsigned int index) { return m_InternalArray[index]; }
      |                             ^~~~~~~~
In file included from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageRegion.h:33,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImage.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageSource.h:32,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageToImageFilter.h:31,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkInPlaceImageFilter.h:31,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkUnaryFunctorImageFilter.h:22,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/itkSurfaceCurvatureBase.h:26,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/ants.h:4,
                 from AddNoiseToImage.cpp:5:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkSize.h:329:29: error: ‘constexpr const value_type& itk::Size<VDimension>::operator[](itk::Size<VDimension>::size_type) const’ cannot be overloaded with ‘constexpr itk::Size<VDimension>::value_type& itk::Size<VDimension>::operator[](itk::Size<VDimension>::size_type) const’
  329 |   constexpr const_reference operator[](size_type pos) const { return m_InternalArray[pos]; }
      |                             ^~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkSize.h:327:23: note: previous declaration ‘constexpr itk::Size<VDimension>::value_type& itk::Size<VDimension>::operator[](itk::Size<VDimension>::size_type) const’
  327 |   constexpr reference operator[](size_type pos) { return m_InternalArray[pos]; }
      |                       ^~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkSize.h:480:1: error: ‘MakeSize’ function uses ‘auto’ type specifier without trailing return type
  480 | auto
      | ^~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkSize.h:480:1: note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkSize.h: In function ‘auto itk::MakeSize(const T ...)’:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkSize.h:483:37: error: use of ‘auto’ in lambda parameter declaration only available with ‘-std=c++14’ or ‘-std=gnu++14’
  483 |   const auto toValueType = [](const auto value) {
      |                                     ^~~~
In file included from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkPoint.h:23,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkContinuousIndex.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageRegion.h:34,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImage.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageSource.h:32,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageToImageFilter.h:31,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkInPlaceImageFilter.h:31,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkUnaryFunctorImageFilter.h:22,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/itkSurfaceCurvatureBase.h:26,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/ants.h:4,
                 from AddNoiseToImage.cpp:5:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVector.h: At global scope:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVector.h:334:1: error: ‘MakeVector’ function uses ‘auto’ type specifier without trailing return type
  334 | auto
      | ^~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVector.h:334:1: note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVector.h: In function ‘auto itk::MakeVector(TValue, const TVariadic ...)’:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVector.h:338:40: error: use of ‘auto’ in lambda parameter declaration only available with ‘-std=c++14’ or ‘-std=gnu++14’
  338 |   const auto assertSameType = [](const auto value) {
      |                                        ^~~~

...

/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkPoint.h: At global scope:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkPoint.h:354:1: error: ‘MakePoint’ function uses ‘auto’ type specifier without trailing return type
  354 | auto
      | ^~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkPoint.h:354:1: note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkPoint.h: In function ‘auto itk::MakePoint(TValue, const TVariadic ...)’:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkPoint.h:358:40: error: use of ‘auto’ in lambda parameter declaration only available with ‘-std=c++14’ or ‘-std=gnu++14’
  358 |   const auto assertSameType = [](const auto value) {
      |                                        ^~~~
In file included from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkContinuousIndex.h:22,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageRegion.h:34,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImage.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageSource.h:32,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageToImageFilter.h:31,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkInPlaceImageFilter.h:31,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkUnaryFunctorImageFilter.h:22,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/itkSurfaceCurvatureBase.h:26,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/ants.h:4,
                 from AddNoiseToImage.cpp:5:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkIndex.h: At global scope:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkIndex.h:417:29: error: ‘constexpr const value_type& itk::Index<VDimension>::operator[](itk::Index<VDimension>::size_type) const’ cannot be overloaded with ‘constexpr itk::Index<VDimension>::value_type& itk::Index<VDimension>::operator[](itk::Index<VDimension>::size_type) const’
  417 |   constexpr const_reference operator[](size_type pos) const { return m_InternalArray[pos]; }
      |                             ^~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkIndex.h:415:23: note: previous declaration ‘constexpr itk::Index<VDimension>::value_type& itk::Index<VDimension>::operator[](itk::Index<VDimension>::size_type) const’
  415 |   constexpr reference operator[](size_type pos) { return m_InternalArray[pos]; }
      |                       ^~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkIndex.h:578:1: error: ‘MakeIndex’ function uses ‘auto’ type specifier without trailing return type
  578 | auto
      | ^~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkIndex.h:578:1: note: deduced return type only available with ‘-std=c++14’ or ‘-std=gnu++14’
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkIndex.h: In function ‘auto itk::MakeIndex(const T ...)’:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkIndex.h:581:37: error: use of ‘auto’ in lambda parameter declaration only available with ‘-std=c++14’ or ‘-std=gnu++14’
  581 |   const auto toValueType = [](const auto value) {
      |                                     ^~~~
In file included from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageSource.h:32,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImageToImageFilter.h:31,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkInPlaceImageFilter.h:31,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkUnaryFunctorImageFilter.h:22,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/itkSurfaceCurvatureBase.h:26,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/ants.h:4,
                 from AddNoiseToImage.cpp:5:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImage.h: At global scope:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImage.h:329:15: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
  329 |   friend std::enable_if_t<std::is_same<TEqualityComparable, TPixel>::value, bool>
      |               ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImage.h:329:10: note: ‘std::enable_if_t’ is only available from C++14 onwards
  329 |   friend std::enable_if_t<std::is_same<TEqualityComparable, TPixel>::value, bool>
      |          ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImage.h:369:15: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
  369 |   friend std::enable_if_t<std::is_same<TEqualityComparable, TPixel>::value, bool>
      |               ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkImage.h:369:10: note: ‘std::enable_if_t’ is only available from C++14 onwards
  369 |   friend std::enable_if_t<std::is_same<TEqualityComparable, TPixel>::value, bool>
      |          ^~~
In file included from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/itkSurfaceCurvatureBase.h:26,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/ants.h:4,
                 from AddNoiseToImage.cpp:5:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:140:18: error: ‘std::enable_if_t’ has not been declared
  140 |             std::enable_if_t<mpl::is_static_castable<TInputPixelType, TOutputPixelType>::value, int> = 0>
      |                  ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:140:29: error: expected ‘>’ before ‘<’ token
  140 |             std::enable_if_t<mpl::is_static_castable<TInputPixelType, TOutputPixelType>::value, int> = 0>
      |                             ^
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:146:18: error: ‘std::enable_if_t’ has not been declared
  146 |             std::enable_if_t<!mpl::is_static_castable<TInputPixelType, TOutputPixelType>::value, int> = 0>
      |                  ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:146:29: error: expected ‘>’ before ‘<’ token
  146 |             std::enable_if_t<!mpl::is_static_castable<TInputPixelType, TOutputPixelType>::value, int> = 0>
      |                             ^
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.h:148:3: error: ‘template<class TInputImage, class TOutputImage> template<class TInputPixelType, class TOutputPixelType, <typeprefixerror><anonymous> > void itk::CastImageFilter<TInputImage, TOutputImage>::DynamicThreadedGenerateDataDispatched(const typename itk::CastImageFilter<TInputImage, TOutputImage>::Superclass::OutputImageRegionType&)’ cannot be overloaded with ‘template<class TInputImage, class TOutputImage> template<class TInputPixelType, class TOutputPixelType, <typeprefixerror><anonymous> > void itk::CastImageFilter<TInputImage, TOutputImage>::DynamicThreadedGenerateDataDispatched(const typename itk::CastImageFilter<TInputImage, TOutputImage>::Superclass::OutputImageRegionType&)’
  148 |   DynamicThreadedGenerateDataDispatched(const OutputImageRegionType & outputRegionForThread);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...

/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.hxx:92:16: error: ‘std::enable_if_t’ has not been declared
   92 |           std::enable_if_t<mpl::is_static_castable<TInputPixelType, TOutputPixelType>::value, int>>
      |                ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.hxx:92:27: error: expected ‘>’ before ‘<’ token
   92 |           std::enable_if_t<mpl::is_static_castable<TInputPixelType, TOutputPixelType>::value, int>>
      |                           ^
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.hxx:114:16: error: ‘std::enable_if_t’ has not been declared
  114 |           std::enable_if_t<!mpl::is_static_castable<TInputPixelType, TOutputPixelType>::value, int>>
      |                ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.hxx:114:27: error: expected ‘>’ before ‘<’ token
  114 |           std::enable_if_t<!mpl::is_static_castable<TInputPixelType, TOutputPixelType>::value, int>>
      |                           ^
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkCastImageFilter.hxx:116:1: error: redefinition of ‘void itk::CastImageFilter<TInputImage, TOutputImage>::DynamicThreadedGenerateDataDispatched(const typename itk::CastImageFilter<TInputImage, TOutputImage>::Superclass::OutputImageRegionType&)’
  116 | CastImageFilter<TInputImage, TOutputImage>::DynamicThreadedGenerateDataDispatched(
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...

In file included from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkRecursiveSeparableImageFilter.h:23,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkRecursiveGaussianImageFilter.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkGradientRecursiveGaussianImageFilter.h:21,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/itkSurfaceImageCurvature.h:20,
                 from /home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ANTsRCore/include/ants.h:6,
                 from AddNoiseToImage.cpp:5:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1054:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1054 | inline std::enable_if_t<mpl::And<mpl::IsArray<TExpr1>, mpl::IsArray<TExpr2>>::Value, unsigned int>
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1054:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1054 | inline std::enable_if_t<mpl::And<mpl::IsArray<TExpr1>, mpl::IsArray<TExpr2>>::Value, unsigned int>
      |        ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1073:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1073 | inline std::enable_if_t<mpl::And<mpl::IsArray<TExpr1>, mpl::Not<mpl::IsArray<TExpr2>>>::Value, unsigned int>
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1073:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1073 | inline std::enable_if_t<mpl::And<mpl::IsArray<TExpr1>, mpl::Not<mpl::IsArray<TExpr2>>>::Value, unsigned int>
      |        ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1089:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1089 | inline std::enable_if_t<mpl::And<mpl::IsArray<TExpr2>, mpl::Not<mpl::IsArray<TExpr1>>>::Value, unsigned int>
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1089:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1089 | inline std::enable_if_t<mpl::And<mpl::IsArray<TExpr2>, mpl::Not<mpl::IsArray<TExpr1>>>::Value, unsigned int>
      |        ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h: In member function ‘unsigned int itk::VariableLengthVectorExpression<TExpr1, TExpr2, TBinaryOp>::Size() const’:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1215:21: error: ‘GetSize’ is not a member of ‘itk::Details’
 1215 |     return Details::GetSize(m_lhs, m_rhs);
      |                     ^~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h: At global scope:
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1263:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1263 | inline std::enable_if_t<Details::op::CanBeAddedOrSubtracted<TExpr1, TExpr2>::Value,
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1263:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1263 | inline std::enable_if_t<Details::op::CanBeAddedOrSubtracted<TExpr1, TExpr2>::Value,
      |        ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1280:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1280 | inline std::enable_if_t<Details::op::CanBeAddedOrSubtracted<TExpr1, TExpr2>::Value,
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1280:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1280 | inline std::enable_if_t<Details::op::CanBeAddedOrSubtracted<TExpr1, TExpr2>::Value,
      |        ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1296:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1296 | inline std::enable_if_t<Details::op::CanBeMultiplied<TExpr1, TExpr2>::Value,
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1296:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1296 | inline std::enable_if_t<Details::op::CanBeMultiplied<TExpr1, TExpr2>::Value,
      |        ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1311:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1311 | inline std::enable_if_t<Details::op::CanBeDivided<TExpr1, TExpr2>::Value,
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1311:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1311 | inline std::enable_if_t<Details::op::CanBeDivided<TExpr1, TExpr2>::Value,
      |        ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1343:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1343 | inline std::enable_if_t<mpl::IsArray<TExpr>::Value, typename TExpr::RealValueType>
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1343:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1343 | inline std::enable_if_t<mpl::IsArray<TExpr>::Value, typename TExpr::RealValueType>
      |        ^~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1355:13: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
 1355 | inline std::enable_if_t<mpl::IsArray<TExpr>::Value, typename TExpr::RealValueType>
      |             ^~~~~~~~~~~
/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkVariableLengthVector.h:1355:8: note: ‘std::enable_if_t’ is only available from C++14 onwards
 1355 | inline std::enable_if_t<mpl::IsArray<TExpr>::Value, typename TExpr::RealValueType>
      |        ^~~

..... continues like that ....

/home/polzehl/R/x86_64-pc-linux-gnu-library/4.2/ITKR/libs/include/ITK-5.3/itkIndex.h:415:80: error: body of ‘constexpr’ function ‘constexpr itk::Index<VDimension>::value_type& itk::Index<VDimension>::operator[](itk::Index<VDimension>::size_type) const [with unsigned int VDimension = 2; itk::Index<VDimension>::reference = long int&; itk::Index<VDimension>::size_type = unsigned int]’ not a return-statement
  415 |   constexpr reference operator[](size_type pos) { return m_InternalArray[pos]; }
      |                                                                                ^
make: *** [/usr/local/lib/R/etc/Makeconf:177: AddNoiseToImage.o] Fehler 1
ERROR: compilation failed for package ‘ANTsR’
* removing ‘/tmp/RtmpZGhikT/Rinst79b942224471/ANTsR’
      -----------------------------------
ERROR: package installation failed

**Comment by dorianps** [comment]
Not sure what the error means, but I think this method requires separate
installation of ITK, ANTsRCore, and ANTsR. I think installing with devtools
may be easier, did you try it?


mydeps <- c( "Rcpp", "RcppEigen", "magrittr", "rsvd", "magic", "psych" )
install.packages( pkgs = mydeps, dependencies = TRUE
)install.packages('devtools')
devtools::install_github('ANTsX/ANTsR')

**Comment by JPolzehl** [comment]
solved with latest commit
