### ISSUE TITLE
Proper similarity metric for Affine registration

### ISSUE THREAD

**Issue by Silvesterrpi** [ANTsX/ANTsR#381]
Hello I am trying to register some animal brain stacks obtained using OCT(Optical coherence tomography) and TPM (Two-Photon Microscopy). I started with Affine transform and planning to apply SyN method later. As for Affine transform, I couldn't get reasonable results in the z dimension with similarity metrics like GC (global correlation) and MI (mutual information), however the result improves a lot when I switch to CC (cross correlation) as the metric. May I know if CC is a proper similarity measure for Affine? I am asking because it is not listed as similarity measure for Affine in the ANTsDoc.

**Comment by ntustison** [comment]
It's probably simply an oversight in the documentation that it's not listed.

**Comment by cookpa** [comment]
It was probably not listed because it's not often used, due to it being much more computationally demanding than GC or MI. But it's fine to use it if it works for you.
