### ISSUE TITLE
aslPerfusion 

### ISSUE THREAD

**Issue by ArzuHas** [ANTsX/ANTsR#386]
**Describe the bug**
I  installed ANTsR package to perform asl image analysis. When I run "aslPerfusion()", I received following error:

                **Error in missing(k) || is.na(k) : 
                  'length = 32' in coercion to 'logical(1)'** 
I tried different version of the packages and update R, as well as different datasets. However, I got same error all the time. Can 

<img width="462" alt="Screen Shot 2023-05-16 at 9 34 36 PM" src="https://github.com/ANTsX/ANTsR/assets/133168107/f919941f-037f-4aeb-a9fc-d0910d54fe19">

I am working on mac os system, the version of R is 4.3.0 and the version of ANTsR is 0.5.7.5

Could you please help me on this issue?
Thanks,
Arzu

**Additional context**

**Comment by stnava** [comment]
are you able to run example data from [here](https://figshare.com/articles/dataset/The_Pediatric_Template_of_Brain_Perfusion_PTBP_/923555) ?

I just ran:

```r

aa=aslPerfusion( asl=img, moreaccurate=1, dorobust=0, mask=msk, N3=TRUE , verbose=TRUE )
```

without any issue and producing:   

![image](https://github.com/ANTsX/ANTsR/assets/324222/ee606a34-e11a-4a5f-8d77-609cce456728)

if you can share your data, we may be able to help more.


```r
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] robust_0.7-1    misc3d_0.9-1    pixmap_0.4-12   ANTsR_0.5.7.5  
[5] ANTsRCore_0.7.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10         mvtnorm_1.1-3       lattice_0.20-45    
 [4] rrcov_1.7-2         MASS_7.3-58.1       grid_4.2.1         
 [7] pcaPP_2.0-3         stats4_4.2.1        magrittr_2.0.3     
[10] robustbase_0.95-0   Matrix_1.5-3        ITKR_0.6.0.0.2     
[13] tools_4.2.1         RcppEigen_0.3.3.9.3 DEoptimR_1.0-11    
[16] fit.models_0.64     compiler_4.2.1      tcltk_4.2.1        
```

**Comment by ArzuHas** [comment]
Thank you very much for your response. It is same when I used the data and tried to update my version to match with yours. Please see the ASL and mask image that I am working on attached. Btw, here is my sessionInfo:
![Screen Shot 2023-05-17 at 3 20 25 PM](https://github.com/ANTsX/ANTsR/assets/133168107/16d4e8dd-3c63-4797-a9db-189ae72613bc)
[ASL.nii.gz](https://github.com/ANTsX/ANTsR/files/11502836/ASL.nii.gz)
[ASLvol0000_bet_mask.nii.gz](https://github.com/ANTsX/ANTsR/files/11502841/ASLvol0000_bet_mask.nii.gz)

All the best,
Arzu

**Comment by stnava** [comment]
could not reproduce the issue with the code below

```r
fn='ASL.nii.gz'
img=antsImageRead(fn)
avg=getAverageOfTimeSeries(img)
msk=getMask(avg)
plot(ts(rowMeans(timeseries2matrix(img,msk))))
aa=aslPerfusion( asl=img, moreaccurate=1, dorobust=0, mask=msk, N3=TRUE , verbose=TRUE )

```

which produced:

![image](https://github.com/ANTsX/ANTsR/assets/324222/918485a2-5534-4ac5-a440-753e8be5e0ef)

no difference when using 
```r
msk=antsImageRead("ASLvol0000_bet_mask.nii.gz")
```
![image](https://github.com/ANTsX/ANTsR/assets/324222/83aa0a30-e02c-4959-b9b3-0f7cd3e505e4)

I do see `warnings` of this nature:

```r
50: In missing(k) || is.na(k) : 'length(x) = 32 > 1' in coercion to 'logical(1)'
```

do you have `warnings=errors` turned on?

**Comment by ArzuHas** [comment]
Yes, I always see exactly same error. 


<img width="232" alt="image" src="https://github.com/ANTsX/ANTsR/assets/133168107/a8878cc9-a500-47d2-b918-7f8442177fe6">

**Comment by ArzuHas** [comment]
When I tried your code above, I got the same error in the stage of "getAverageOfTimeSeries(img)"

![Screen Shot 2023-05-17 at 4 15 46 PM](https://github.com/ANTsX/ANTsR/assets/133168107/b347ba2b-da89-4b90-a4d3-3c1683031da7)

**Comment by stnava** [comment]
do you have warnings=errors turned on?

try to set options(warn=0) or options(warn=1) in your R session

**Comment by ArzuHas** [comment]
Yes unfortunately, I see when I have errors turned on:

![Screen Shot 2023-05-17 at 4 38 42 PM](https://github.com/ANTsX/ANTsR/assets/133168107/04dc193a-d97c-4175-9e4f-5b770b3b049a)

**Comment by stnava** [comment]
this commit should address your issue https://github.com/ANTsX/ANTsR/commit/d2824a6f1ee0f4a7e3ba472772cd310ed1c78577

however, you will have to compile from source to get it

**Comment by ArzuHas** [comment]
It worked! I am grateful for your help!

Arzu

**Comment by ArzuHas** [comment]
Hi,
Actually, it was a false alarm. Although it did not give an error for the first parts, I saw the same error after a while of processing of aslPerfusion command such as:
![Screen Shot 2023-05-17 at 5 58 41 PM](https://github.com/ANTsX/ANTsR/assets/133168107/af08d6d3-c331-409e-b772-6beed9384e68)
