### ISSUE TITLE
ITK_GLOBAL_NUMBER_OF_THREADS is ignored

### ISSUE THREAD

**Issue by muratmaga** [ANTsX/ANTsR#390]
I am trying to do measure performance scaling for a project and this code executes pretty much the same amount of time regardless of what I set the ITK_GLOBAL_NUMBER_OF_THREADS to. I tried setting in R with Sys.setenv and also in shell prior to starting R. Both had no effect

```R


fi <- antsImageRead(getANTsRData("r16") ) %>% resampleImage(., c(1024, 1024), useVoxels = TRUE)
mi <- antsImageRead(getANTsRData("r64") ) %>% resampleImage(., c(1024, 1024), useVoxels = TRUE)

f=function(X) {
  antsRegistration(fi, mi, "SyNOnly",  
                   synMetric="CC", 
                   synSampling=4, synits="0x0x0x1000", 
                   smoothingsigmas="3x2x1x0" 
                   shrinkfactors="4x3x2x1")
}
  
cores=c(64, 32, 16, 8, 4)

time=NULL
for (i in cores){
Sys.setenv(ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=i)
tt=Sys.time()
f(i)
time=rbind(time, cbind(i, Sys.time()-tt))
}
```

This is not a big deal for me, as I typically prefer to use the full number of cores. I wanted to let people now.

**Comment by dorianps** [comment]
I think setting it in the console should work fine. See this old thread for
some tests I ran long time ago.

https://github.com/dorianps/LESYMAP/issues/15

**Comment by muratmaga** [comment]
Thanks. I retried with the using the terminal window in the Rstudio, and yes setting the variable prior to starting R works.
