### ISSUE TITLE
Resampling an image to source image geometry

### ISSUE THREAD

**Issue by SlicerMorph** [ANTsX/ANTsR#399]
I have a segmentation from Slicer which was unfortunately cropped to the minimum extends of the labelmap. While this lines up correctly wrt to the source volume  in physical space, I need to resample segmentation to the exact dimensions of the source volume. Is there a specific function to do that? I couldn't tweak the resampleImage or makeImage to meet my needs. Here is what data looks like:

```
> label
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 79x124x239 
  Voxel Spacing       : 1x1x1 
  Origin              : -92 -55 92 
  Direction           : -1 0 0 0 -1 0 0 0 1 
  Filename           : Female_AAZE_K2270-45_cleaned.seg.nrrd 

> img
antsImage
  Pixel Type          : float 
  Components Per Pixel: 1 
  Dimensions          : 259x258x421 
  Voxel Spacing       : 1x1x1 
  Origin              : 0 0 0 
  Direction           : -1 0 0 0 -1 0 0 0 1 
  Filename           : ../imagesTr/Female_AAZE_K2270-45-e15.5_Baiap2.nrrd 
```

**Comment by muratmaga** [comment]
Exactly, thank you very much. Not sure why my autocompete didn't display it...
