### ISSUE TITLE
Landmark transform

### ISSUE THREAD

**Issue by zarquon42b** [ANTsX/ANTsR#59]
Hi,
is there currently a way to calculate 
a) a simple landmark transform (like vtkLandmarkTransform) and apply it to an image or
b) intitialise the registration based on landmarks
?

Best 
Stefan

**Comment by stnava** [comment]
(a)   is in ANTs [here](https://github.com/stnava/ANTs/blob/master/Examples/ANTSUseLandmarkImagesToGetAffineTransform.cxx)  ... it is very simple and could easily be wrapped for R

(b) in `antsRegistration` , there is `initialTransform` which should allow you to take output from (a) and initialize the image registration ... not sure how tested this is ...

**Comment by zarquon42b** [comment]
Thank you, I will look into that. At the moment I am using https://github.com/zarquon42b/RvtkStatismo/blob/master/src/vtkImageTransform.cpp to do this in R based on simple kx3 matrices, But I was trying to avoid an additionally dumping step.

Best
Stefan

**Comment by stnava** [comment]
here is some R code that i dont have time to explain at the moment but might be useful:

```
library(ANTsR)
library(RANN)
library(MASS)
chk3<-data.frame( x=c(82.5,137.5,78.5,197.5,192.5,275.5),
                  y=c(116.5,35.5,253.5,147.5,236.5,232.5))
chk4<-data.frame( x=c(4.5,1.09091,59.5,114.5,146.5,198.50000),
                  y=c(128.5,37.5,277.5,115.5,197.5,154.5))
lm2aff<-function( lm1, lm2  )
  {
  penalty=0
  if ( penalty > 1 ) penalty<-1
  if ( penalty < 0 ) penalty<-0
  xc=colMeans(lm1)
  x=lm1
  for ( i in 1:length(xc) )
    x[,i]=x[,i]-xc[i]
  y=lm2
  for ( i in 1:length(xc) )
    y[,i]=y[,i]-xc[i]
  mdl<-lm( y ~ x )
  mdl2<-lm( lm2 ~ lm1 )
  mdl2inv<-lm( lm1 ~ lm2  )
  yp<-predict(mdl)
  center<-xc
  mm<-coefficients(mdl)
  trans=mm[1,]
  mat=t(mm[2:nrow(mm),])
  # itk format affine transform
  tx=data.frame( center=center, trans=trans, mat=mat )
  disp<-( predict(mdl) - x )
  return( list(disp=disp, tx=tx, mdl=mdl2, mdlinv=mdl2inv ) )
  }
lm2rig<-function( lm1, lm2  )
  {
  xc=colMeans(lm1)
  x=lm1
  for ( i in 1:length(xc) )
    x[,i]=x[,i]-xc[i]
  yc=colMeans(lm2)
  y=lm2
  for ( i in 1:length(yc) )
    y[,i]=y[,i]-yc[i]
  hmat<-matrix( rep(0,length(yc)^2) , ncol=length(yc) )
  for ( i in 1:nrow(x))
    hmat<-hmat+outer(x[i,],y[i,])
  hsvd<-svd(hmat)
  rot=hsvd$v %*% diag(length(hsvd$d)) %*% t(hsvd$u)
  # see https://github.com/oleg-alexandrov/projects/blob/master/eigen/Kabsch.cpp
  tran = (yc - rot %*% xc );
  xt = t( rot %*% t(lm1) )
  for ( i in 1:length(xc) )
    xt[,i]<-xt[,i]+tran[i]
  return( list(rot=rot, tran=tran, center=xc ) )
  }
applyTx<-function( x, center, mdl ) {
  xt=x
  for ( i in 1:ncol(x) )
    {
    xt[,i]=xt[,i]-center[i]
    }
  return( predict( mdl, newdata=data.frame(xt) ) )
}
applyTxr<-function( x, tran, rot ) {
  xt = t( rot %*% t(x) )
  for ( i in 1:length(tran) )
    xt[,i]<-xt[,i]+tran[i]
  return(xt)
  }
tx<-lm2aff( data.matrix(chk3), data.matrix(chk4)  )
chk3to4<-applyTx( chk3, tx$center, tx$mdl )
chk4to3<-applyTx( chk4, tx$center, tx$mdlinv )
print( mean(colMeans(abs(chk4-chk3to4)) ))
print( mean(colMeans(abs(chk3-chk4to3)) ))
txr<-lm2rig( data.matrix(chk3), data.matrix(chk4)  )
chk3to4<-applyTxr( data.matrix(chk3), txr$tran, txr$rot )
print( mean(colMeans(abs(chk4-chk3to4)) ))
```

**Comment by stnava** [comment]
note that these transformations would still have to be written out to itk's .mat format to be useful in `antsRegistration`

**Comment by zarquon42b** [comment]
Thanks again.

**Comment by ntustison** [comment]
This is an updated version 

https://github.com/stnava/ANTs/blob/master/Examples/antsLandmarkBasedTransformInitializer.cxx

which combines the two previous classes for affine/rigid and b-spline transforms.

**Comment by stnava** [comment]
yes - sorrry @ntustison , i forgot about that much superior application!

**Comment by zarquon42b** [comment]
Awesome, in case you are interested, I wrote a function to create label images (of class antsImage) from landmark coordinates (I will add examples and docu tomorrow): https://github.com/zarquon42b/RANTs/blob/master/R/signedDist.r#L70
which I can then use to get the intital transform: and it seems to work excellently.
BTW: are you planning to wrap this within ANTsR?

Best
Stefan

**Comment by stnava** [comment]
ok - let us know when you get the function roxygen ready and we can add it.

i, personally, did not have plans to wrap the landmark stuff for ANTsR.  though any contribution toward that end would be welcomed ...

**Comment by zarquon42b** [comment]
Hi,
* What I actually meant was if you plan to include the antsLandmarkBasedTransformInitializer stuff ... but I roxygenized ```points2LabelImage``` anyway: https://github.com/zarquon42b/RANTs/blob/master/R/antsPoints2LabelImage.r if you consider it useful, please include it.
* Additionally, I started wrapping ```antsLandmarkBasedTransformInitializer```, and while passing character strings to files on disk, I could not yet figure out how to pass pointers as arguments.
* Finally, I figured out how to save an affine transformation matrix into itk's mat format and wrote a function to create and save a transforms (rigid, affine and similarity) calculated from landmarks: https://github.com/zarquon42b/RANTs/blob/master/R/getAffine.r#L38 , it will be saved as matlab v4 file using RcppOctave

Have a nice weekend
Stefan

**Comment by stnava** [comment]
these look quite useful - am happy to look over a pull request.

one simple (ish) example of how to pass pointers is here:  https://github.com/stnava/ANTsR/blob/master/src/sccaner.cpp

**Comment by stnava** [comment]
update:

* should wrap [antsLandmarkBasedTransformInitializer.cxx](https://github.com/stnava/ANTs/blob/master/Examples/antsLandmarkBasedTransformInitializer.cxx) for ANTsR

* potentially integrate with @jeffduda efforts on `antsTransforms` ( see vignettes )
    * e.g. read/write antsTransform objects
    * alternatively pass these directly to ants registration objects

**Comment by stnava** [comment]
Finally addressed in patchMatchR
