### ISSUE TITLE
ANTsR on ShinyApps.io?

### ISSUE THREAD

**Issue by dorianps** [ANTsX/ANTsR#92]
Has anyone tried or succeeded to interface ANTsR in [Shinyapps.io](http://www.shinyapps.io/) ? When I tried few months ago it did not work, the problem being the installation of ANTsR in Shinyapps server.

If we had an interface like Shinyapps, we could create simple (or complex?) tools for online use. It would be ideal if someone wants just to try a specific ANTsR tool without going through the burden of installing R/ANTsR and all the other required packages.

**Comment by muschellij2** [comment]
To my knowledge, Shinyapps does not allow non-CRAN packages.  I have ANTsR
on our private server, but not on shinyapps.

**Comment by stnava** [comment]
should be possible to implement a shiny application and host it on one's own server.   alternatively, request special dispensation from the shiny app folks ... never know, they may accommodate you.

**Comment by muschellij2** [comment]
Shinyapps now takes GitHub packages.  I still am struggling to get ANTsR to install without having a shinyapps timeout error.

**Comment by stnava** [comment]
Can you install from binary?

On Wednesday, July 13, 2016, John Muschelli <notifications@github.com>
wrote:

> Shinyapps now takes GitHub packages. I still am struggling to get ANTsR to
> install without having a shinyapps timeout error.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/stnava/ANTsR/issues/92#issuecomment-232463676>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AATyfupMulu-Xap01dxz5hcSt3NUJgkGks5qVT7CgaJpZM4HuMkV>
> .
>


-- 

brian

**Comment by muschellij2** [comment]
I don't know if you can deploy a binary on their system.

John

**Comment by dorianps** [comment]
Any luck on this?
It would be so great to have a web interface for users to try the tools built in ANTsR.

**Comment by muschellij2** [comment]
Have you tried this lately @dorianps ?

**Comment by dorianps** [comment]
Nope, no plans to try either, too many things going on for now.

**Comment by muratmaga** [comment]
I would imagine memory would be a serious constrain for free instances. They are configured with 1g or less last time I tried to use for something else..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
